### ISSUE TITLE
test benchmarks with Jackson 2.15.0-rc1

### ISSUE THREAD

**Issue by pjfanning** [plokhotnyuk/jsoniter-scala#1003]
* should fix the issue in https://github.com/FasterXML/jackson-module-scala/issues/609
* this release adds StreamReadFeature.USE_FAST_BIG_NUMBER_PARSER that should be set to true along with StreamReadFeature.USE_FAST_DOUBLE_PARSER
* v2.15.0 has a [StreamReadConstraints](https://github.com/FasterXML/jackson-core/blob/2.15/src/main/java/com/fasterxml/jackson/core/StreamReadConstraints.java) with some defaults that might cause issues in some edge cases

You can make the limits effectively unlimited by creating a JsonFactory that overrides the default StreamReadConstraints.
An example that increases the max number len:
```
   val jsonFactory = JsonFactory.builder()
     .streamReadConstraints(StreamReadConstraints.builder().maxNumberLength(Integer.MAX_INTEGER).build())
     .build()
```

**Comment by plokhotnyuk** [comment]
Hi, @pjfanning !

Thanks for reaching me here and sharing updates that you have done for `jackson-module-scala`!

I'm happy that your projects also value security, correctness, and performance.

Please review [the latest version of object mapping configurations](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-benchmark/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/benchmark/JacksonSerDesers.scala).

I'll run benchmarks during the week. Probably, the following upcoming optimization for `uPickle` will be picked too: https://github.com/com-lihaoyi/upickle/pull/467

**Comment by plokhotnyuk** [comment]
Done, results are published [here](https://plokhotnyuk.github.io/jsoniter-scala/) as usually.
