### ISSUE TITLE
Can't serializie ±∞ values.

### ISSUE THREAD

**Issue by krux02** [plokhotnyuk/jsoniter-scala#1010]
trying to serialize a double value of ∞ will result raise "JsonWriterException: illegal number: Infinity". This is a common problem of json, it lacks an answer to the question of how + and - infinity should be serialized. A workaround to not violate the json spec would be, to encode numbers into string literals, but in jsoniter, this doesn't help much as it also raises the exact same exception. I was hoping that I would find an option in the jsoniter config to deal with this, but I did not find anything to help me here.

The data that I am currently work with does occasionally contain ±∞ values and I have to ensure that they survive the json roundtrip.

**Comment by plokhotnyuk** [comment]
Hi, Arne! Please test if [this](https://github.com/plokhotnyuk/jsoniter-scala/blob/478503e4ecbd02fbcbcac285b89b540c4e741ce8/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L614-L637) custom codec works for you when pasted as an implicit value in the scope of the `make` call.

**Comment by krux02** [comment]
Thanks a lot. This does solve the problem. I didn't know I can overload parsing behavior of primitive types. I was only looking in the configuration object.
