### ISSUE TITLE
error when using circe in Jsoniter

### ISSUE THREAD

**Issue by krux02** [plokhotnyuk/jsoniter-scala#1013]
We am currently in the transition from circe to Jsoniter. For this transition the json serialization between circe and jsoniter must be compatible. Unfortunately somebody put a circe.JsonObject as a member of a case class. I don't know how to deal with it. There is a circe sub project that I tried, but it doesn't do what I expect it to do? Anyway, here is the error that I get when I try to use it.

```scala
package nocode.common

import com.github.plokhotnyuk.jsoniter_scala.macros._
import com.github.plokhotnyuk.jsoniter_scala.core._
import com.github.plokhotnyuk.jsoniter_scala.circe._
import io.circe.JsonObject

case class Plugin(
  name: String,
  status: Int,
  data: String,
  externalData: JsonObject,
)

object JsoniterFarts {
  implicit val codecPlugin: JsonValueCodec[Plugin] = JsonCodecMaker.make[Plugin]
}
```

```
[error] /home/arne/proj/priceloop/nocode/common/src/main/scala/nocode/common/bugreport.scala:16:73: 'fields' parameter of 'io.circe.JsonObject.MapAndVectorJsonObject' should be defined as 'val' or 'var' in the primary constructor.
[error]   implicit val codecPlugin: JsonValueCodec[Plugin] = JsonCodecMaker.make[Plugin]
[error]  
```

I have no idea what to do about this error message. It is pretty much unhelpful as I have no control ovor the source code where the error comes up.

**Comment by krux02** [comment]
thanks for the feedback. I is really helpful. I found out that the json object isn't used at all on this side. It is just used to store some data, that needs to be kept around and is later sent back on the wire.  I can't leave it out from the case class, but I can change the type. So my solution was to just change it to `Json` and it worked. But really think you for your answer It is nice to know that it would actually work with JsonObject as well, even though JsonObject (form some reasion :shrug: ) doesn't inherit from `Json`. But it would be enough, if the entire subtree of the json would be stored in a string literal, as well. Is there a way to do that?

**Comment by plokhotnyuk** [comment]
More efficient way it just grabbing `externalData` value to some byte array as a raw JSON value like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/9f4f4546d1930f0ebfe84e55b7de4205d8b93939/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L841-L870). 

It will have the minimal footprint in memory and will not spend CPU cycles on encoding when storing.

**Comment by krux02** [comment]
Thanks a lot, this solves everything for me.
