### ISSUE TITLE
How do I encode an enum in circe style?

### ISSUE THREAD

**Issue by krux02** [plokhotnyuk/jsoniter-scala#1014]
Currently I have an enum that is stored in the database like this `{"EnumValue":{}}` instead of `"EnumValue"` or `{"type":"EnumValue"}`. This style comes from circe serialization. Is there an easy option to get this style of serilization with jsoniter as well? I know by now how I can write my own custom serializer, but maybe there is an easier way to make this happen by default with more types.

I have another small question. I've tried several times to call `JsoniterCodecMaker.make[MyType](myConfig)`, the function does exist, but I get weird compilation errors about compilation that I don't understand. I didn't figure out yet how to actually pass a config to `make`. Is there an explanation for that?

**Comment by plokhotnyuk** [comment]
Hi, Arne! Thanks for your feedback again!

There are a couple of special macros for derivation of codecs that are compatible with circe: `JsoniterCodecMaker.makeCirceLike` and `JsoniterCodecMaker.makeCirceLikeSnakeCased`. But they worked not properly with Scala objects. I'm going to fix it and cut a new release ASAP.

Using those macros should help you avoid unexpected compilation errors that are described in the 2nd item of the Know Issues list: https://github.com/plokhotnyuk/jsoniter-scala#known-issues

**Comment by plokhotnyuk** [comment]
@krux02 Please pick the `v2.23.0` release and use `JsoniterCodecMaker.makeCirceLike` or `JsoniterCodecMaker.make(CodecMakerConfig.withCirceLikeObjectEncoding(true).withDiscriminatorFieldName(None))`.

To reuse configuration for the `make` call you can use techniques described [here](https://github.com/plokhotnyuk/jsoniter-scala/issues/999#issuecomment-1450158768)

**Comment by krux02** [comment]
Thanks a lot, this really helps.
