### ISSUE TITLE
Add Support Scala 3 Enums

### ISSUE THREAD

**Issue by pme123** [plokhotnyuk/jsoniter-scala#1071]
Is there a plan to support Scala3 enums?
This is possible with circe, and the main reason I cannot try jsoniter-scala;).

see https://scalajobs.com/blog/enum-serialization-in-scala/

**Comment by plokhotnyuk** [comment]
@pme123 Hi, Pascal!

Scala 3 enums are supported already and there are examples of their usage [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerNewEnumSpec.scala) in tests.

So... you should try jsoniter-scala definitely :D

**Comment by williamhaw** [comment]
hi @plokhotnyuk I have a use case which doesn't seem to be covered by the unit tests:

```
import com.github.plokhotnyuk.jsoniter_scala.core._
import com.github.plokhotnyuk.jsoniter_scala.macros._
import java.util.UUID

enum AccountType:
  case CASH, MUTUAL_FUNDS

given codecAccountType: JsonValueCodec[AccountType] = JsonCodecMaker.make(
  CodecMakerConfig.withDiscriminatorFieldName(None)
)

case class Account(accountId: UUID, accountType: AccountType = AccountType.CASH)

given codecAccount: JsonValueCodec[Account] = JsonCodecMaker.make

class SerializationTestSuite extends munit.FunSuite {

  test("test serialisation") {
    val output = writeToString(AccountType.MUTUAL_FUNDS)
    assertEquals(output, "\"MUTUAL_FUNDS\"")

    val output2 = writeToString(Account(UUID.fromString("bd292b55-d6f0-489a-bb83-3dc31a30d2b0"), AccountType.CASH))
    assertEquals(output2, "{\"accountId\":\"bd292b55-d6f0-489a-bb83-3dc31a30d2b0\", \"accountType\": \"CASH\"}")
  }
}
```

fails with:
```
SerializationTestSuite.example test that succeeds - munit.ComparisonFailException: /Users/william/Play/serialization-test/src/test/scala/SerializationTestSuite.scala:23
22:    val output2 = writeToString(Account(UUID.fromString("bd292b55-d6f0-489a-bb83-3dc31a30d2b0"), AccountType.CASH))
23:    assertEquals(output2, "{\"accountId\":\"bd292b55-d6f0-489a-bb83-3dc31a30d2b0\", \"accountType\": \"CASH\"}")
24:  }
values are not the same
=> Obtained
{"accountId":"bd292b55-d6f0-489a-bb83-3dc31a30d2b0"}
=> Diff (- obtained, + expected)
-{"accountId":"bd292b55-d6f0-489a-bb83-3dc31a30d2b0"}
+{"accountId":"bd292b55-d6f0-489a-bb83-3dc31a30d2b0", "accountType": "CASH"}
```

**Comment by plokhotnyuk** [comment]
Hi, @williamhaw! Thanks for trying jsoniter-scala!

I your example works as expected. The default configuration produces codecs that doesn't serialise default values defined in the case class definition.

Use the following derivation configuration to enforce serialisation on defaults:
```scala
given codecAccountType: JsonValueCodec[AccountType] = JsonCodecMaker.make(CodecMakerConfig.withTransientDefault(false))
```

**Comment by plokhotnyuk** [comment]
@pme123  @williamhaw I hope that I answered your questions.

Please, feel free to reopen it or submit a new one if you have some feedback or questions related to Scala 3 enum support.
