### ISSUE TITLE
Consider pointing source maps to github

### ISSUE THREAD

**Issue by raquo** [plokhotnyuk/jsoniter-scala#1087]
We were talking about bundle sizes, and this reminded me of this.

For scala.js libraries, source maps are generated at compile time – i.e. when you compile before publishing, so either on your computer, or in CI. Source maps point to original source files, and so by default, they include the paths of those files on the computer where this compilation took place. To be clear, not the end user's computer, but your (the library publisher's) computer.

Those paths are specific to your computer (e.g. /Users/plokhotnyuk/projects/....) and are not available on the end users' computer, and so the source maps become broken in various tools that use them to display original source code. For example, I noticed this in `source-map-explorer`, the npm package I use to analyze JS bundle sizes. (that tool still works, but e.g. chrome dev tools would not be able to show original source code).

The fix is pretty easy – we can point the source maps to github URLs instead. This is how you can do it:

```scala
    // In build.sbt, for the scala.js project(s):
    scalacOptions += {
      val localSourcesPath = baseDirectory.value.toURI
      val remoteSourcesPath = s"https://raw.githubusercontent.com/plokhotnyuk/jsoniter-scala/${git.gitHeadCommit.value.get}/"
      val sourcesOptionName = if (scalaVersion.value.startsWith("2.")) "-P:scalajs:mapSourceURI" else "-scalajs-mapSourceURI"

      s"${sourcesOptionName}:$localSourcesPath->$remoteSourcesPath"
    }
```

Note that the snippet above contains your username/projectname on github, and the sbt git plugin inserts the commit hash, to build a valid URL for your open source files hosted on github.

For this to work, you need the sbt git plugin:

```
// in plugins.sbt
addSbtPlugin("com.github.sbt" % "sbt-git" % "2.0.1")
```

This is pretty common config for libraries published for Scala.js, I've used it in my own libraries with no issue. If you need a working reference, here is a small but [cross published library](https://github.com/raquo/Waypoint/blob/master/build.sbt) that has this done.

PS thanks for this nice JSON library!

**Comment by plokhotnyuk** [comment]
@raquo Thank you a lot for the feedback and support!

I've cut a new release with the fix that you proposed:
https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v2.24.1

Probably, there is a room for improvements in Scala.JS modules of the project.

As an example, I don't know how to fix the following warning related to source maps for [the benchmark page](https://plokhotnyuk.github.io/jsoniter-scala/scala-3-fullopt.html):
![image](https://github.com/plokhotnyuk/jsoniter-scala/assets/890289/7c7ac1e5-4511-44ed-b1eb-d619bd7a4ff8)

**Comment by raquo** [comment]
Awesome, thanks for the release, I'll try it out as soon as I can!

First, I'm getting a different error from my Chrome dev tools:
![Screen Shot 2023-10-06 at 03 03 45](https://github.com/plokhotnyuk/jsoniter-scala/assets/532656/5bd97020-a564-4e82-9778-27eb7e53da52)

That is telling me that Chrome expects the source map for https://plokhotnyuk.github.io/jsoniter-scala/scala-3/jsoniter-scala-benchmark-jsdeps.min.js to be published at https://plokhotnyuk.github.io/jsoniter-scala/scala-3/jsoniter-scala-benchmark-jsdeps.min.js.map (note the .map at the end). If you are also getting this error (note that it's not about FileSaver), and want to see source maps in the browser, you need to put that `-jsdeps.min.js.map` file in the same directory as the `-jsdeps.min.js` file, and have them both published to the web. Your Scala.js config and bundler config can be set to generate source maps – this slows down compilation, but it's useful in fullLinkJS mode. If you already have this config, you should be able to find the .map files locally, next to the generated .js files.

The FileSaver error that you screenshotted though is a bit different. Your `-jsdeps.min.js` file includes the `FileSaver.min.js` dependency, and includes this line after it: `//# sourceMappingURL=FileSaver.min.js.map`. To be honest I'm not quite sure why this was left in. This looks wrong in the context of your bundle. It gives us an invalid URL, which is why the sourcemap tooling chokes on it.

Are you by any chance using a very old version of FileSaver, perhaps as a transitive dependency? I found [this issue](https://github.com/eligrey/FileSaver.js/issues/481) but not sure if it's related. If this FileSaver error is the only issue then the problem is probably specific to how the problematic version of FileSaver was published, or perhaps to how some other library included it, if it's a transitive dependency.
