### ISSUE TITLE
Parsing failure on `Either` type

### ISSUE THREAD

**Issue by iblislin** [plokhotnyuk/jsoniter-scala#1091]
Hi,
MWE here, with scala 3.3.1

```scala
  test("either should work"):
    val json: String = """{"foo": [1, 2, 3]}"""

    case class Foo(foo: Either[Int, List[Int]])

    given JsonValueCodec[Foo] = JsonCodecMaker.make[Foo]
    readFromString[Foo](json)
```

Output:
```
==> X JSONSerdesTest.either should work  0.001s com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected '{', offset: 0x00000008, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00000000 | 7b 22 66 6f 6f 22 3a 20 5b 31 2c 20 32 2c 20 33 | {"foo": [1, 2, 3 |
| 00000010 | 5d 7d                                           | ]}               |
+----------+-------------------------------------------------+------------------+
```

**Comment by plokhotnyuk** [comment]
Hi Iblis,

By default, the `make` call for `Either` generate a codec for sum-types.

In your case you have two options:
1. replace  `Either[Int, List[Int]]` by `::[Int]`;
2. use a custom codec like this: 
```scala
      implicit val customCodecOfEither: JsonValueCodec[Either[Int, List[Int]]] =
        new JsonValueCodec[Either[Int, List[Int]]] {
          private val codecOfList = JsonCodecMaker.make[List[Int]]

          def nullValue: Either[Int, List[Int]] = null

          def decodeValue(in: JsonReader, default: Either[Int, List[Int]]): Either[Int, List[Int]] = {
            val t = in.nextToken()
            in.rollbackToken()
            if (t != '[') Left(in.readInt())
            else Right(codec.decodeValue(in, Nil))
          }

          def encodeValue(x: Either[Int, List[Int]], out: JsonWriter): Unit = x match {
            case Left(i) => out.writeVal(i)
            case Right(l) => codecOfList.encodeValue(l, out)
          }
        }
```

**Comment by iblislin** [comment]
I'm curious about the case that `make` works by default. Could you show one?

**Comment by plokhotnyuk** [comment]
> I'm curious about the case that `make` works by default. Could you show one?

[Here](https://github.com/plokhotnyuk/jsoniter-scala/blob/8942d7c83e46a06274199cc66e2e501083102724/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L2505-L2508) is a test for a representation of `Either` that stay the same for Scala 2 and Scala 3.

**Comment by iblislin** [comment]
> [Here](https://github.com/plokhotnyuk/jsoniter-scala/blob/8942d7c83e46a06274199cc66e2e501083102724/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L2505-L2508) is a test for a representation of Either that stay the same for Scala 2 and Scala 3.

Ah, thanks for the pointer!

I finally figured out the concepts of "discriminator field" in it and `sealed traits` plus `withDiscriminatorFieldName` meets my needs.
Maybe we could add more pointers (or texts) for the concepts. For me, it's kind of obscure, if I only read the README.

**Comment by iblislin** [comment]
a side issue: how to make `withFieldNameMapper` works with `withDiscriminatorFieldName` to control the serialized field name?
e.g. I have an input json `{"myType": "foo", ...}`, then I want to serialize it as `{"category": "foo", ...}` later.

**Comment by plokhotnyuk** [comment]
> a side issue: how to make `withFieldNameMapper` works with `withDiscriminatorFieldName` to control the serialized field name? e.g. I have an input json `{"myType": "foo", ...}`, then I want to serialize it as `{"category": "foo", ...}` later.

Mappers for field and discriminator name works independent, except for case when there is a JSON key clash that is checked in compile-time and [reported as a compiler error](https://github.com/plokhotnyuk/jsoniter-scala/blob/f68fa76181b1940ec046265308af80ace2d257b8/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L1695-L1699).

**Comment by plokhotnyuk** [comment]
> Maybe we could add more pointers (or texts) for the concepts. For me, it's kind of obscure, if I only read the README.

Currently, I'm preparing Tutorial and How To Guide.

Until they are published, please skim through test sources of `core` and `macros` modules for more understanding about how their features work.

**Comment by iblislin** [comment]
> Mappers for field and discriminator name works independent, except for case when there is a JSON key clash that is checked in compile-time and [reported as a compiler error](https://github.com/plokhotnyuk/jsoniter-scala/blob/f68fa76181b1940ec046265308af80ace2d257b8/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L1695-L1699).

Okay, I worked out a solution via the Chimney library.
