### ISSUE TITLE
Scala3 w/ -Yexplicit-nulls mode enabled, compile error

### ISSUE THREAD

**Issue by vspiridenkov** [plokhotnyuk/jsoniter-scala#1095]
jsoniter-scala version is:
2.24.2

compile error description:
[error]   18 |  given jsonCodec: JsonValueCodec[Box] = JsonCodecMaker.make
[error]      |                                         ^^^^^^^^^^^^^^^^^^^
[error]      |                                         Found:    String | Null
[error]      |                                         Required: String
[error]      |--------------------------------------------------------------------------
[error]      |Inline stack trace
[error]      |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]      |This location contains code that was inlined from JsonCodecMaker.scala:2899
[error]      |- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
[error]      |This location contains code that was inlined from JsonCodecMaker.scala:2899
[error]       --------------------------------------------------------------------------

possible patch to solve this error:
```patch
--- a/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala
+++ b/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala
@@ -2895,8 +2895,8 @@ object JsonCodecMaker {
             else '{ $out.writeNonEscapedAsciiVal($matching) }
           } else {
             val tx = x.asExprOf[java.lang.Enum[_]]
-            if (encodingRequired) '{ $out.writeVal($tx.name) }
-            else '{ $out.writeNonEscapedAsciiVal($tx.name) }
+            if (encodingRequired) '{ $out.writeVal($tx.name.nn) }
+            else '{ $out.writeNonEscapedAsciiVal($tx.name.nn) }
           }
         } else if (isEnumOrModuleValue(tpe) || tpe =:= TypeRepr.of[None.type]) withEncoderFor(methodKey, m, out) { (out, x) =>
           '{
```

Bug reproduce example [build.sbt]:
```scala
scalaVersion := "3.3.1"
scalacOptions ++= Seq(
  "-release", "17",
  "-deprecation",
  "-feature",
  "-Yexplicit-nulls",
  "-explain",
)
run / fork := true
run / connectInput := true
libraryDependencies ++= Seq(
  "com.github.plokhotnyuk.jsoniter-scala" %% "jsoniter-scala-core" % "2.24.2",
  "com.github.plokhotnyuk.jsoniter-scala" %% "jsoniter-scala-macros" % "2.24.2" % "compile-internal"
)
```

Bug reproduce example [Main.scala]:
```scala
import com.github.plokhotnyuk.jsoniter_scala.macros.{JsonCodecMaker, CodecMakerConfig, named}
import com.github.plokhotnyuk.jsoniter_scala.core.{JsonValueCodec, JsonReader, JsonWriter, writeToArray, readFromArray, writeToString}

enum Color extends Enum[Color] {
  case red
  case green
}

case class Box (
  color: Color
)
object Box {
  given jsonCodec: JsonValueCodec[Box] = JsonCodecMaker.make
}

@main
def main(): Unit = {
  val box = Box(Color.red)
  println(s">>> ${writeToString(box)(Box.jsonCodec)}")
}
```

**Comment by plokhotnyuk** [comment]
@vspiridenkov Please check [the latest release with a fix](https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v2.24.3)

For similar cases you can use a workaround proposed in the related issue: https://github.com/plokhotnyuk/jsoniter-scala/issues/988

**Comment by vspiridenkov** [comment]
Thanks for fast response and fix. Good advice to use scala.language.unsafeNulls.

There is one more issue with enum in key position - possible fix:
```diff
diff --git a/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala b/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala
index 1b27aa27c..ed336ca42 100644
--- a/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala
+++ b/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala
@@ -1307,7 +1307,7 @@ object JsonCodecMaker {
             if (encodingRequired) '{ $out.writeKey($matchExpr) }
             else '{ $out.writeNonEscapedAsciiKey($matchExpr) }
           } else {
-            val nameExpr = Apply(Select.unique(x.asTerm, "name"), List()).asExprOf[String]
+            val nameExpr = Typed(Apply(Select.unique(x.asTerm, "name"), List()), TypeIdent(TypeRepr.of[String].typeSymbol)).asExprOf[String]
             if (encodingRequired) '{ $out.writeKey($nameExpr) }
             else '{ $out.writeNonEscapedAsciiKey($nameExpr) }
           }
```

**Comment by plokhotnyuk** [comment]
@vspiridenkov Thanks for reporting and proposed fix.

Finally, in a fix I reused solution from generation of writing Java enum as JSON values.

Please peek the latest release with the fix: https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v2.24.4
