### ISSUE TITLE
Wondering.. do you use the io.circe package to get privilidged access to Circe AST? 

### ISSUE THREAD

**Issue by benhutchison** [plokhotnyuk/jsoniter-scala#1096]
Apologies for using an issue to ask a question.

I noticed that part of Jsoniter codebase is placed into the `io.circe` package. Wanted to ask whether this was to workaround Circe's attempt to encapsulate its data types?

Circe has, IMO, an excessive level of privacy for its core data types, which can frustrate both usability and particularly performance. For little benefit in my estimation. I've hit this in my own work and it seems jsoniter might have too.

**Comment by plokhotnyuk** [comment]
@benhutchison No problems, Ben! Thanks for the question.

The short answer - yes.

As I recall it was done only to access to `JNumber`.

**Comment by benhutchison** [comment]
TY 👍
