### ISSUE TITLE
Is Fury faster than Jsoniter?

### ISSUE THREAD

**Issue by objektwerks** [plokhotnyuk/jsoniter-scala#1097]
See this JMH benchmark run: https://github.com/objektwerks/fury

I was surprised given all the **fury** about Fury performance.

Am I doing something wrong in this JMH perf test?

**Comment by plokhotnyuk** [comment]
@objektwerks I'm not surprised that parsing/serialization from/to `String` is slow.

Have you tried `readFromArray` and `writeToArray` instead?

**Comment by objektwerks** [comment]
It's Fury that's slower!

1. jsoniterBenchmark 0.243
2. furyBenchmark 0.470

And I thought Fury would be faster. :)

**Comment by plokhotnyuk** [comment]
Yep, as a binary serializer it should be faster, especially when working with primitives.

Please see a list of proposed improvements for your benchmarks: https://github.com/objektwerks/fury/pull/1

**Comment by objektwerks** [comment]
Thanks!
