### ISSUE TITLE
Using `writeToArray` for performance boost

### ISSUE THREAD

**Issue by samuelorji** [plokhotnyuk/jsoniter-scala#1104]
Hi, 

First of all, amazing job.

I have a question about using the `writeToArray` method [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/34237425a1a8a14eb31638b26c0ab7a7fdcc97b9/jsoniter-scala-core/js/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/package.scala#L415), I can see that the Json writer is backed by a ThreadLocal object. Does this then mean that it's safe to use in the context of a [Play Action](https://www.playframework.com/documentation/2.9.x/ScalaActions#What-is-an-Action?) where the default executor is a fork-join?

For example, in the play application docs [here](https://www.playframework.com/documentation/2.9.x/ScalaJsonHttp#Serving-a-list-of-entities-in-JSON), we simply return a json object (JsValue):

```scala
def listPlaces() = Action {
  val places : List[Place] = ???
  val json = Json.toJson(places)
  Ok(json)
}
```

The problem with this method is that the `places` object is first serialized into a JsValue in `Json.toJson`, that `JsValue` is [then serialized into a ByteArray](https://github.com/playframework/playframework/blob/f74c2340962b69b389e89c67a30aa474aa6a1958/core/play/src/main/scala/play/api/http/Writeable.scala#L106), whereas with jsoniter,  I can just directly serialize the places object into a byte array using the `writeToArray` method and [therefore skip](https://github.com/playframework/playframework/blob/f74c2340962b69b389e89c67a30aa474aa6a1958/core/play/src/main/scala/play/api/http/Writeable.scala#L206) the intermediate `JsValue` representation like this:

```scala
def listPlaces() = Action {
  val places : List[Place] = ???
  Ok(writeToArray(map)).as(ContentTypes.JSON)
}

```

My question here is if this is safe to do and pitfalls I should be aware off considering [this warning](https://github.com/plokhotnyuk/jsoniter-scala/blob/34237425a1a8a14eb31638b26c0ab7a7fdcc97b9/jsoniter-scala-core/js/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/package.scala#L404)

Thank you

**Comment by plokhotnyuk** [comment]
@samuelorji Hi, Samuel!

Thanks for trying the library!

The most efficient way is using of pre-allocated arrays with `writeToSubArray`.

But `writeToArray` calls are more expensive and do an array allocation for each result array. 

Additional re-allocations of internal buffers (thread-local) can happen with `writeToArray` when your output exceed default value of `WriterConfig.preferredBufSize` which is 32K currently. To avoid them you should pass an additional configuration parameter with the same optimal value of buffer size for all calls in the same thread pool.

I will fix the description of `WriterConfig.preferredBufSize` in API docs and mention all these pitfalls.

The warning is for rare cases when you use custom codecs with `writeTo...` calls, like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/34237425a1a8a14eb31638b26c0ab7a7fdcc97b9/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L915).

**Comment by samuelorji** [comment]
@plokhotnyuk Thanks for your response.

`writeToSubArray` would have been the best option, but how possible is it to know the predefined size of the json (or case class) beforehand in order to know the optimal size of a preallocated array so as not to run into an `ArrayIndexOutOfBoundsException`  because the buffer used underneath [isn't growable](https://github.com/plokhotnyuk/jsoniter-scala/blob/34237425a1a8a14eb31638b26c0ab7a7fdcc97b9/jsoniter-scala-core/js/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/core/package.scala#L468).

So using our example:
```scala
def listPlaces() = Action {
  val places : List[Place] = ???
  val placesArray : Array[Byte] = Array.ofDim(???) // can one know this size ?
  val written = writeToSubArray(map, placesArray, 0, placesArray.length)
  Ok().as(ContentTypes.JSON)
}
```


Also, what do you mean by pre-allocated arrays in `writeToSubArray` vs an array allocation in `writeToArray`, in the case of a play Action, even with `writeToSubArray`, one will have to allocate an array for each response that the json will be serialized into, whereas with `writeToArray`, the allocation is done for you

**Comment by plokhotnyuk** [comment]
Yes, the size of pre-allocated arrays should be less than max size of serialized responses to avoid `ArrayIndexOutOfBoundsException`.

You can relay on `writeToArray` for precisely allocated output arrays, but just to avoid redundant allocations of internal buffers please specify a preferred buffer sizes in `config: WriteConfig` when calling it. 

The performance difference of perfectly tuned `writeToArray` and properly allocated `writeToSubArray` calls you can see in results of `*.jsoniterScala` and `*.jsoniterScalaPrealloc` benchmarks accordingly [here](https://plokhotnyuk.github.io/jsoniter-scala/index.html) and [here](https://plokhotnyuk.github.io/jsoniter-scala/index-t16.html).

**Comment by samuelorji** [comment]
Thank you so much. Appreciate your hardwork
