### ISSUE TITLE
Path of the field with error

### ISSUE THREAD

**Issue by kachaps4u** [plokhotnyuk/jsoniter-scala#1129]
Hello!
Let's say we have nested class:

eg: 
`Address(streetName: String, city: String, state: String)`
`Person(name: String, address: Option[Address])`

If state is missing, then I want to get the path as $.address.state, but I am getting the message as:
`missing required field "state"`

How do we resolve this?

In Jackson, we have Reference inside JsonMappingException to iterate and find the correct path

**Comment by plokhotnyuk** [comment]
Capturing JSON object keys and JSON array indexes for errors during parsing adds a lot of overhead that is paying in the happy path.

You can estimate that overhead by comparing with benchmark results for real-world API message samples between jsoniter-scala and smithy4s [here](https://plokhotnyuk.github.io/jsoniter-scala).

By default jsoniter-scala adds an exact position offset and optionally a hex dump of the affected place of the input that should be enough for debugging.
