### ISSUE TITLE
AnyVal round-trip not working as expected

### ISSUE THREAD

**Issue by anoto-moniz** [plokhotnyuk/jsoniter-scala#1140]
Hello!
We're working on migrating from json4s to jsoniter-scala, and hitting an issue with inlining. We have a similar setup to #1078 , but instead of a nested object, it's a `Map[String, CustomType]`.

Here's a simplified view of the structure.

```
trait TopProperty extends Any
trait Property extends Any with TopProperty
case class DoubleProperty(value: Double) extends AnyVal with Property
case class StringProperty(value: String) extends AnyVal with Property

case class Container(
  name: String,
  properties: Map[String, Property],
  other: OtherCustomType
)
```

The JSON we need to support is

```
{"name": "foo", "properties": {"a": 4.0, "b": "bar"}, "other": {...}}
```

The encoding/serialization works as desired, producing the above JSON. But when I try to deserialize it using `readFromString[Container]`, I get `expected '{'` at the position of the first value (`4.0` in the example above). I've been unable to figure out why this asymmetry is occurring.

I've tried a bunch of other approaches, but the only one I've had success with is directly using the `JsonWriter` and `JsonReader` objects in a custom codec, which of course isn't ideal. Especially since the real class has about a dozen fields, a handful of which are complex classes.

**Comment by plokhotnyuk** [comment]
@anoto-moniz Thanks for reporting!

If generated codec cannot parse own output then it is an error definitely.

As a workaround for your case if there are no more other implementation of `Property` the following custom codec could be used:
```scala
implicit val customCodecOfProperty: JsonValueCodec[Property] =
  new JsonValueCodec[Property] {
    def nullValue: Property = null

    def decodeValue(in: JsonReader, default: Property): Property = {
      val t = in.nextToken()
      in.rollbackToken()
      if (t == '"') StringProperty(in.readString(null))
      else DoubleProperty(in.readDouble())
    }

    def encodeValue(x: Property, out: JsonWriter): _root_.scala.Unit = x match {
      case DoubleProperty(i) => out.writeVal(i)
      case StringProperty(s) => out.writeVal(s)
    }
  }
```

Is it acceptable solution for you?

Do you have possibility to change definition of your data structures for more clear solution?

**Comment by plokhotnyuk** [comment]
@anoto-moniz Please peek the latest release where codecs will not be generated for sum types with leaf classes that are `AnyVal` or one value classes with `CodecMakerConfig.withInlineOneValueClasses(true)`.

**Comment by anoto-moniz** [comment]
@plokhotnyuk Thanks so much for the quick response! I updated my code with your suggested codec, and it works like a charm.

And I don't think the limitation you reference should cause my other use cases any problems. This use of sum types without type discriminators is unique in our codebase.
