### ISSUE TITLE
ZIO-HTTP / Jsoniter [ unexpected end of input error ]

### ISSUE THREAD

**Issue by objektwerks** [plokhotnyuk/jsoniter-scala#1173]
>***This is NOT a priority issue for me, at all!*** ***I simply want my code to work! :)***

>In this code snippet, Jsoniter throws an `unexpected end of input error` exception:
```
object Server extends ZIOAppDefault:
  val routes: Routes[Handler, Response] =
    Routes(
      Method.POST / "command" -> handler: (request: Request) =>
        for
          json    <- request.body.asString(Charsets.Utf8)
          _       <- Console.printLine(s"*** MediaType: ${request.body.mediaType.get.fullType} Json: $json")
          command =  readFromString[Command](json) // `unexpected end of input error` exception thrown here!
          _       <- Console.printLine(s"*** Command: $command")
          handler <- ZIO.service[Handler]
          event   <- handler.handle(command)
          _       <- Console.printLine(s"*** Event: $event")
        yield Response.json( writeToString[Event](event) )
    ).handleError( _ match
      case error: Throwable =>
        val fault = Fault(s"*** Invalid json: ${error.getMessage}")
        val json  = writeToString[Fault](fault)
        Response.json(json)
    )
```
>The code can be viewed here: [Server.scala](https://github.com/objektwerks/pool.balance.z/blob/main/server/src/main/scala/objektwerks/Server.scala)

>Here's a test code snippet:
```
  def register =
    val register = writeToString[Register](Register(emailAddress))
    val request  = Request.post(url, Body.fromString(register).contentType(MediaType.application.json))
    for
      response   <- Server.routes.runZIO(request)
      json       <- response.body.asString
      registered =  readFromString[Registered](json)
    yield
      account = registered.account
      assertTrue(account.isActivated)
```
>The code can be viewed here: [IntegrationTest.scala](https://github.com/objektwerks/pool.balance.z/blob/main/server/src/test/scala/objektwerks/IntegrationTest.scala)

>See [Notes](https://github.com/objektwerks/pool.balance.z/blob/main/README.md) for additional details.

>The project can be downloaded here: [pool.balance.z](https://github.com/objektwerks/pool.balance.z). Simply run ```sbt clean test``` to view debug and errors.

>Thanks in advance for any comments on this issue! Cheers! :)

**Comment by plokhotnyuk** [comment]
@objektwerks Thanks for the question!

The source of problem is that when working with sum types no need to derive codecs for leaf types.

So you should have only 3 givens for each sum type:
```scala
  given JsonValueCodec[Entity] = JsonCodecMaker.make[Entity](CodecMakerConfig.withDiscriminatorFieldName(None))
  given JsonValueCodec[Command] = JsonCodecMaker.make[Command](CodecMakerConfig.withDiscriminatorFieldName(None))
  given JsonValueCodec[Event] = JsonCodecMaker.make[Event](CodecMakerConfig.withDiscriminatorFieldName(None))
```
then in your tests instead of 
```scala
writeToString[Register](Register(emailAddress))
...
readFromString[Registered](json)
```
you should write
```scala
writeToString[Command](Register(emailAddress))
...
readFromString[Event](json)
```

Also, don't forget to fix error writing line in your server:
```scala
        val json  = writeToString[Event](fault)
```

**Comment by objektwerks** [comment]
All of your changes and a few of my own worked! My IntegrationTest now passes! Thanks, once again, for your help! Cheers! :)
