### ISSUE TITLE
How to customize serialization of a key of a Map

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [plokhotnyuk/jsoniter-scala#1185]
I've created a new tag in [stackoverflow.com](http://stackoverflow.com/): `jsoniter-scala`.  

And here is my question: https://stackoverflow.com/questions/78922229/how-to-customize-serialization-of-a-key-of-a-map-with-jsoniter

I copy the contents of the question:

I have a claas that jsoniter is able to create automatically a custom codec, except for the key of a map.

How to create a custom codec just for the key?

case class ApiTreeNode(
    value: String,
    label: String,
    field: String,
    path: List[Int],
    icon: Option[IconReference],
    statistics: Map[TreeStatisticOperation, Option[Double]],
  )
In this example, I need only to customize how `TreeStatisticOperation` is handled, and avoid writing a codec that handles all the details.

**Comment by plokhotnyuk** [comment]
@DavidPerezIngeniero Thanks for the question! It should be definitely covered in some "How-to" section of docs.

The suggest approach to define and implement `given JsonKeyCodec[TreeStatisticOperation]` before derivation of codec for `ApiTreeNode` is the best approach.

See [tests](https://github.com/plokhotnyuk/jsoniter-scala/blob/69e63417b2c5bc52d21715d0e591e86f2d12f3b8/jsoniter-scala-macros/shared/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L572-L610) for more examples of `JsonKeyCodec` implementations.

**Comment by DavidPerezIngeniero** [comment]
This solves the problem, thanks.
Custom codec should use `out.writeKey()` or `out.writeVal()`

What is best for asking questions?

- stackoverflow
-  issues in github

**Comment by plokhotnyuk** [comment]
If you want a response as fast as possible then search and ask on the StackOverflow site.

Opening questions here is a good approach too. 

Most of your questions will be included in upcoming "How-to" docs.

Thanks for all your feedback!
