### ISSUE TITLE
Codec derivation in Scala 3.5

### ISSUE THREAD

**Issue by olafmaurer** [plokhotnyuk/jsoniter-scala#1187]
In scala 3.4, the following worked:

`import com.github.plokhotnyuk.jsoniter_scala.core.*`
`import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker`
`import utils.tagging.Tags.{@@, tag}`

`inline given tagJsonValueCodec[V, T]: JsonValueCodec[V @@ T] = new JsonValueCodec[V @@ T]:`
 `val codec: JsonValueCodec[V]                                      = JsonCodecMaker.makeCirceLikeSnakeCased`
 `override def decodeValue(in: JsonReader, default: V @@ T): V @@ T = tag[T](codec.decodeValue(in, default: V))`
`override def encodeValue(x: V @@ T, out: JsonWriter): Unit        = codec.encodeValue(x, out)`
`override def nullValue: V @@ T = tag [T] (codec.nullValue)`
  
  
Upgrading to Scala 3.5, this yields the warning

> [warn] 7 |inline given tagJsonValueCodec[V, T]: JsonValueCodec[V @@ T] = new JsonValueCodec[V @@ T]:
> [warn]   |                                                                   ^
> [warn]   |     New anonymous class definition will be duplicated at each inline site

so the code was changed to 

>[same imports]
`inline given tagJsonValueCodec[V, T]: JsonValueCodec[V @@ T] with`
 `val codec: JsonValueCodec[V]                                      = JsonCodecMaker.makeCirceLikeSnakeCased`
 `override def decodeValue(in: JsonReader, default: V @@ T): V @@ T = tag[T](codec.decodeValue(in, default: V))`
`override def encodeValue(x: V @@ T, out: JsonWriter): Unit        = codec.encodeValue(x, out)`
`override def nullValue: V @@ T                                    = tag[T](codec.nullValue)`
  
  which does not work, it gives
  

> [error] -- Error: [...]/jsoniterCodecs.scala:8:70 
> [error] 8 |  val codec: JsonValueCodec[V]                                      = JsonCodecMaker.makeCirceLikeSnakeCased
> [error]   |                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> [error]   |No implicit 'com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec[_ >: scala.Nothing <: scala.Any]' defined for 'tagJsonValueCodec.this.V'.

Is this some known issue? Any suggestions?

**Comment by olafmaurer** [comment]
Relevant tagging implementation:

`  opaque type Tagged[+V, +Tag] = Any`
`type @@[+V, +Tag]            = V & Tagged[V, Tag]`

`def tag[Tag]: [V] => V => V @@ Tag = [V] => (v: V) => v`

**Comment by plokhotnyuk** [comment]
@olafmaurer Thanks for opening an issue!

I'm going to reproduce it and check what is happening in generated code using ` given CodecMakerConfig.PrintCodec = new CodecMakerConfig.PrintCodec {}`.

**Comment by plokhotnyuk** [comment]
It is a bug that could be reproduces even in Scala 2 for generic `implicit def`.

To see how many instances of codecs instantiated just need to add `println("+1")` after `val codec ...` line.

As a workaround you can convert `tagJsonValueCodec` to simple `def` and derive codecs for each tagged type, like here:
```scala
//> using dep "com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core::2.30.9"
//> using compileOnly.dep "com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros::2.30.9"

import com.github.plokhotnyuk.jsoniter_scala.macros._
import com.github.plokhotnyuk.jsoniter_scala.core._

object Tags {
  opaque type Tagged[+V, +Tag] = V

  type @@[+V, +Tag] = V & Tagged[V, Tag]

  def tag[Tag]: [V] => V => V @@ Tag = [V] => (v: V) => v
}

object Graph {
  import Tags.{@@, tag}

  def tagJsonValueCodec[V, T](codec: JsonValueCodec[V]): JsonValueCodec[V @@ T] = new JsonValueCodec[V @@ T]:
    println("+1")
    override def decodeValue(in: JsonReader, default: V @@ T): V @@ T = tag[T](codec.decodeValue(in, default: V))
    override def encodeValue(x: V @@ T, out: JsonWriter): Unit = codec.encodeValue(x, out)
    override def nullValue: V @@ T = tag[T](codec.nullValue)

  trait NodeIdTag

  type NodeId = Int @@ NodeIdTag

  case class Node(id: NodeId, name: String)
  case class Edge(node1: NodeId, node2: NodeId)
  case class NodeProduct(left: Option[Node], right: Option[Node])
}

//given CodecMakerConfig.PrintCodec = new CodecMakerConfig.PrintCodec {}
given JsonValueCodec[Graph.NodeId] = Graph.tagJsonValueCodec(JsonCodecMaker.make)

given JsonValueCodec[Graph.Node] = JsonCodecMaker.make
given JsonValueCodec[Graph.Edge] = JsonCodecMaker.make
given JsonValueCodec[Graph.NodeProduct] = JsonCodecMaker.make

println(readFromString[Graph.Node]("""{"id":1,"name":"VVV"}""")())
println(readFromString[Graph.Edge]("""{"node1":1,"node2":2}""")())
println(readFromString[Graph.NodeProduct]("""{"left":{"id":1,"name":"VVV"},"right":{"id":1,"name":"VVV"}}""")())
```

**Comment by olafmaurer** [comment]
Thanks for the workaround, it was successfully applied :)

**Comment by plokhotnyuk** [comment]
@olafmaurer I'm happy to see that it was acceptable for you.

Probably it will be possible to add a new feature to avoid need of custom codec creation by introducing acceptance of implicit conversions available in the scope of `make` calls, like here:
```scala
val nodeCodec: JsonValueCodec[Node] = {
  implicit def convertToTagged[V, Tag](v: V): V @@ Tag = v.asInstanceOf[V @@ Tag]

  make[Node]
}
```

**Comment by plokhotnyuk** [comment]
@olafmaurer @nkgm Reaching you here to point on a generalized workaround proposed in [this](https://github.com/plokhotnyuk/jsoniter-scala/commit/d1951eebf4f7439b13509fe2d2714b9f0896119f) commit.

You still need to provide codecs for types to be used with tags.

Would it be more acceptable for you?

**Comment by nkgm** [comment]
Hi @plokhotnyuk, I'm not sure how this relates to my self-type issue?

**Comment by plokhotnyuk** [comment]
> Hi @plokhotnyuk, I'm not sure how this relates to my self-type issue?

It is not related your your issue directly. I just saw your code samples with tagged types.

**Comment by plokhotnyuk** [comment]
Tried the following script with `scala-cli` and it works fine:
```scala
//> using dep "com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-core::2.30.9"
//> using compileOnly.dep "com.github.plokhotnyuk.jsoniter-scala::jsoniter-scala-macros::2.30.9"
//> using scala 3.5.0

import com.github.plokhotnyuk.jsoniter_scala.core.*
import com.github.plokhotnyuk.jsoniter_scala.macros.JsonCodecMaker.*

object Tags {
  opaque type Tagged[+V, +T] = Any

  type @@[+V, +T] = V & Tagged[V, T]

  def tag[T]: [V] => V => V @@ T = [V] => (v: V) => v

  inline given[V, T] (using c: JsonValueCodec[V]): JsonValueCodec[V @@ T] = c.asInstanceOf[JsonValueCodec[V @@ T]]
}

import Tags.*

implicit val intCodec: JsonValueCodec[Int] = make
implicit val stringCodec: JsonValueCodec[String] = make

trait NodeIdTag

type NodeId = Int @@ NodeIdTag

trait NodeNameTag

type NodeName = String @@ NodeNameTag

case class Node(id: NodeId, name: NodeName)

case class Edge(n1: NodeId, n2: NodeId)

println(readFromString("""{"id":1,"name":"VVV"}""")(make[Node]))
println(readFromString("""{"n1":1,"n2":2}""")(make[Edge]))
```

**Comment by nkgm** [comment]
> It is not related your your issue directly. I just saw your code samples with tagged types.

Ah, so more of an extra point. That has always worked for me, but you just gave me this idea:
```scala
inline given [F[_], V, T](using c: F[V]): F[V @@ T] = c.asInstanceOf[F[V @@ T]]
```

Now `Tags` can happily live in my `Predef` library while taking care of its implicits.

**Comment by plokhotnyuk** [comment]
> ```scala
> inline given [F[_], V, T](using c: F[V]): F[V @@ T] = c.asInstanceOf[F[V @@ T]]
> ```
Wow! Such universal solution for all type classes!

**Comment by plokhotnyuk** [comment]
To avoid anonymous class duplication just need to create a named class and use it like [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/141bf0bb9c1b72c7da13ca6396c7f393a3c5515c#diff-101da10875561876cd7d91b51de347b28a9f5b85f2c8b95d156f10d9a2925ed1R21).

To reduce number of created codec instances during derivation create them manually and share using `given` or `implicit val` like [here](https://github.com/plokhotnyuk/jsoniter-scala/issues/1187#issuecomment-2326993641).
