### ISSUE TITLE
Avoid inline given

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [plokhotnyuk/jsoniter-scala#1193]
I've read in the doc this:

> Do not use implicit def and inline given methods for generation of custom codes. Scala 3.5.0+ shows compilation time warning New anonymous class definition will be duplicated at each inline site for some inline given cases, but for other use cases the compiler will silently generate duplicated codec instances. To mitigate that convert methods of codec generation to def and explicitly derive custom codecs, like here:

I do not fully understand your example.

My simplified case:

```Scala
sealed trait A

object A:
   given JsonValueCodec[A] = make

case class B[T <: A](number: Int, value: T)
````
How to make a codec for `B`?
If I changed the B definition to this, it would be trivial, but I would lose type info:
```Scala
class B:
   number: Int
   value: A
````

**Comment by DavidPerezIngeniero** [comment]
In my simple case, what would be the correct way to do it?

**Comment by plokhotnyuk** [comment]
Both ways are correct functionally, but the way with mitigation will allocate less memory and be more efficient in runtime.

**Comment by DavidPerezIngeniero** [comment]
So, i I have:
````
sealed trait A
class A1(...) extends A
class A2(...) extends A
....
class An(...) extends A

class B[T <: A]:
   number: Int
   value: T

object A:
   given JsonValueCodec[A1] = make
   given JsonValueCodec[A2] = make
   ....
   given JsonValueCodec[An] = make
```
would be the best way of creating the necesary codecs.
Wouldn't it?

**Comment by plokhotnyuk** [comment]
If you will derive codecs for leaf types of sum type then you will loose the discriminator field (`"type": "A1"`, `"type": "A2"`, etc.) in JSON representation.

**Comment by DavidPerezIngeniero** [comment]
That's true.

Then the siimplest solution I can imagine  is to build a custom codec for `B`.
The hardest part (building the codec for `A`) can be done automaically by jsoniter.

**Comment by plokhotnyuk** [comment]
I don't understand the reason of defining `B` in a generic way `case class B[T <: A]` while `A` is a `sealed trait`.

Why you cannot define `case class B(number: Int, value: A)`? Could you please explain me your case?
