### ISSUE TITLE
Example how to handle union of case clasess

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [plokhotnyuk/jsoniter-scala#1208]
Is there an example of how to build a custom deserializer with minimum manual work and easy maintenance, when there a several case clasess?
Each case class can have many fields.

Example:
```Scala
case class A(a: Int, b: String)
case class B(a: Boolean)

type All = A | B

given JsonMakerCodec[All] with
   override def decodeValue(in: JsonReader, default: All): All = ???
   ...
```
Writing the encoder is really easy.

**Comment by plokhotnyuk** [comment]
@DavidPerezIngeniero Please add expected JSON representation for possible values.

Why do you use `type All = A | B` instead of:
```scala
enum All:
  case A(a: Int, b: String)
  case B(a: Boolean)  
```
?

**Comment by DavidPerezIngeniero** [comment]
Because it can be 3rd party classes, like `java.util.Date`

I'm converting code that uses `Any` by union classes, and I'm discovering by trial and error, which types can be `Any`.

**Comment by plokhotnyuk** [comment]
It is almost impossible to derive automatically codecs for arbitrary union types.

I will be happy to help you with your concrete cases.

For that I need your expected JSON samples and definitions of data types and understanding what could be changed or tuned in them to simplify derivation of codecs.

As an example, [this](https://github.com/plokhotnyuk/jsoniter-scala/blob/4064bf308c86e0c07fa9edb0f632aeefa978596f/jsoniter-scala-macros/shared/src/test/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerNewTypeSpec.scala#L157-L263) codec can parse any JSON samples to some recursive data structure based on union types with Scala 3.3.x, but recursion for union types is not supported in latest versions even using that hack with type matching.

**Comment by DavidPerezIngeniero** [comment]
Until I debug, I don't know how it is expected JSON.

**Comment by DavidPerezIngeniero** [comment]
An idea is to parse objects to an intermediate `Map[String, Any]`, and then try to guess the type.

In this way, the guessing code will be simpler and it won't have to deal to low level stream stuff.

**Comment by plokhotnyuk** [comment]
If you see some benefits of intermediate in-memory representation for JSON then you can try [this](https://github.com/plokhotnyuk/jsoniter-scala/blob/2bcbeed66ab30bdd279ce6cecbabd41bf814bd70/jsoniter-scala-circe/shared/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/circe/JsoniterScalaCodec.scala#L30-L47) codec that uses circe's AST and check if it will be helpful in your guessing journey.

**Comment by DavidPerezIngeniero** [comment]
Thanks.
