### ISSUE TITLE
Incorrect "missing required field" exception message

### ISSUE THREAD

**Issue by megaserg** [plokhotnyuk/jsoniter-scala#134]
Hello!
I have observed the behavior that seems like a bug to me. Tested on latest master (9bd990c). It seems like the problem is in the way the `checkReqVars` works with the bitpacking. Will be happy to help fixing if that's indeed a bug.
Please find the diff with a failing test case attached: [0001-add-test.patch.txt](https://github.com/plokhotnyuk/jsoniter-scala/files/2177879/0001-add-test.patch.txt)
Thanks!

**Steps to reproduce:**
- Have a class like `case class TwoKeys(key1: Option[Long], key2: Long)`
- `key1` is optional, `key2` is required
- Parse a string that doesn't contain `key2`
- An exception is thrown.

**Expected behavior:**
The exception should complain about missing required field `key2` and should not complain about missing optional field `key1`.

**Actual behavior:**
The exception complains about missing required field `key1`.

Failing test output after applying the patch above:
```
[info]   "missing required field "key1", offset: 0x00000001, buf:
[info]              +-------------------------------------------------+
[info]              |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
[info]   +----------+-------------------------------------------------+------------------+
[info]   | 00000000 | 7b 7d                                           | {}               |
[info]   +----------+-------------------------------------------------+------------------+" did not contain "missing required field "key2", offset: 0x00000001" (JsonCodecMakerSpec.scala:889)
```

**Comment by plokhotnyuk** [comment]
@megaserg Nice catch, Serg!

It definitely a bug and affects all fields except 1st, 33th, 65th, 99th, etc.

**Comment by plokhotnyuk** [comment]
@megaserg Thanks a lot, Serg!
Release with fixes is available on the Maven Central: https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v0.29.1

**Comment by plokhotnyuk** [comment]
Yes, you are right.

With this duplicated code of macro I just tried to generate cleaner code for most cases when we have less than 32 fields in a class (please see it using the `-Xmacro-settings:print-codecs` option for `scalac` which [prints sources of generated codecs in compile time](https://github.com/plokhotnyuk/jsoniter-scala/blob/5a44081dfa4f637e1125d2b9861535d1cf6c64ad/jsoniter-scala-macros/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala#L1025)).

Also, in general, an implementation of macro for `JsonValueCodec` worth more caring for much cleaner code and reusage by extentions .
