### ISSUE TITLE
Support Top Level Arrays

### ISSUE THREAD

**Issue by shawjef3** [plokhotnyuk/jsoniter-scala#155]
If I have a codec for A, I shouldn't have to do anything to get a codec for Seq[A].

In other words, the following should compile.

```scala
type MyType
implicit val c: JsonValueCodec[MyType] = ???
writeToStream(???: Seq[MyType], ???: OutputStream)
```

**Comment by shawjef3** [comment]
Furthermore, when the type in the Seq is not a JSON object, it should automatically get a codec.

Examples:

```scala
writeToStream(Seq(1,2,3), ???: OutputStream)
````

```scala
writeToStream(Seq(Seq("hi"), Seq("bye")), ???: OutputStream)
````

**Comment by plokhotnyuk** [comment]
jsoniter-scala supports top-level arrays or Scala collections, but do not derive any top-level codec implicitly.
Please see any example from tests - all top-level codecs should be derived by explicit call of the `make` macro with specified type: 
https://github.com/plokhotnyuk/jsoniter-scala/blob/1189beff5211a73a28bccad7a18362252c0c8d5a/jsoniter-scala-macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala
