### ISSUE TITLE
write java.time.localDate 

### ISSUE THREAD

**Issue by benoit-ponsero** [plokhotnyuk/jsoniter-scala#162]
Hello,

java.time.* types seems to be supported so i have a case class like this for testing:

```scala
case class Created(
  localDate:LocalDate=LocalDate.now,
  localDateTime: LocalDateTime=LocalDateTime.now,
  time:LocalTime=LocalTime.now
)
object Created {
  implicit val codec: JsonValueCodec[Created] = JsonCodecMaker.make[Created](CodecMakerConfig(skipUnexpectedFields = false))
}
```

Here is the result of writeToArray :
```json
{"localDateTime":"2018-10-04T11:42:16.849","time":"11:42:16.849"}
```

I don't understand why **localDate** field is skipped even with skipUnexpectedFields = false. 

I have another question about date pattern. 

Can we custom the output pattern of localDate & localDateTime ? 

Thanks

**Comment by plokhotnyuk** [comment]
Hi, @benoit-ponsero !

You have used configuration the `skipUnexpectedFields` flag which is turn off skipping of unexpected key-values pairs during parsing of JSON. This flag do not affect serialization.

Currently all definitions of default values in the primary constructor make field optional for parsing and serialization. It allow to minimize using of `Option[A]` wrapers if you have some reasonable defaults.

In your case for using of `.now` you will got empty JSON objects on warmed JVM.
Just run the following code snippet on Scastie to see them alter several iterations: https://scastie.scala-lang.org/9tAmjMIESvaXlQkuvXhaGQ

Built in codecs for `java.time._` works only with ISO-8601 representation, so if you need different format then write custom codecs and make them to be visible in the implicit scope of the `JsonCodecMaker.make[Created]` call. Here are examples of custom codec usage in tests:
https://github.com/plokhotnyuk/jsoniter-scala/blob/master/jsoniter-scala-macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L398-L504

**Comment by benoit-ponsero** [comment]
ok, thanks for the explanations. 
it's strange that it's just affect the field "localDate". 

I understand this behavior for parsing but seems a bit dangerous for writing. 
Your example is a good workaround but is quite verbose. 
Is there a way to turn off this for writing ? 

Thanks again for your help and your good work !

**Comment by plokhotnyuk** [comment]
I have added the transientDefault flag for the CodecMakerConfig to allow turning off skipping of serialization of field values which matched with defaults: https://github.com/plokhotnyuk/jsoniter-scala/commit/f38e48b102f74330bb2b3ae736d546734e34be23

**Comment by plokhotnyuk** [comment]
v0.33.0 release with this commit is already available on the Maven Central: 
http://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-macros_2.12/0.33.0/

**Comment by benoit-ponsero** [comment]
Thanks a lot !
