### ISSUE TITLE
Enable serializing of default valued fields if needed

### ISSUE THREAD

**Issue by landler** [plokhotnyuk/jsoniter-scala#163]
It would be useful if there was an option to enable the serialization of fields that have default values (to provide "dense" output instead of the current sparse output).

i.e. being able to disable this feature (from README.md) when serializing:
> Fields with values that are equals to default values, or are empty options/collections/arrays are not serialized to provide a sparse output

I tried searching for an easy way to get these fields serialized without modifying all my case classes or creating custom codecs for them, but couldn't find an easy solution unfortunately - I'd love to be pointed in the right direction if this is already easily possible!

**Comment by plokhotnyuk** [comment]
v0.33.0 release with this commit is already available on the Maven Central: 
http://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-macros_2.12/0.33.0/

**Comment by plokhotnyuk** [comment]
@landler have you had a chance to try generate your codecs with this flag turned off?

**Comment by landler** [comment]
Thank you! Yes, works great - this was exactly what I needed, thanks for the insanely fast response & feature implementation!
