### ISSUE TITLE
Better handling of NaN and Infinity

### ISSUE THREAD

**Issue by nilskp** [plokhotnyuk/jsoniter-scala#245]
```java
java.io.IOException: illegal number: Infinity
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.encodeError(JsonWriter.scala:223)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeFloat(JsonWriter.scala:1546)
	at com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeVal(JsonWriter.scala:352)
```

There's a couple of things I'd like to see addressed here:

* More specific exception would be nice
* Better yet, a configuration option for dealing with `NaN` and `-Infinity`/`Infinity`.

For the latter, I would personally prefer to have those invalid values emitted as Strings. This will allow seamless consumption for Javascript if wrapping in `Number`, i.e.

```javascript
val fpNumber = Number(json.myfp);
```

Other options could be emit `null` or don't emit field at all.

Thoughts?

**Comment by plokhotnyuk** [comment]
@nilskp I have pushed to the master changes for exceptions: https://github.com/plokhotnyuk/jsoniter-scala/commit/753650b4e1082fe52ea2df8e57626d077ab1dab5

Next step will be adding an option proposed by you for parsing and serialization of non-finite floats and doubles.

**Comment by plokhotnyuk** [comment]
Finally considered that best option is using a custom codec for double.
