### ISSUE TITLE
Adding methods on JsonWriter to write raw data

### ISSUE THREAD

**Issue by cchafer** [plokhotnyuk/jsoniter-scala#249]
HI,
I'm facing a case where I have to embed a Json object into another one.

An example always being simpler, this is what I have

```
final case class Payload(jsonifiedContent: Array[Byte]) // could be string or any other underlying type
final case class Event(id: Int, date: ZonedDateTime, data: Payload)
```

I want user to be able to create Payload, without knowing about Event internals.
So I create Events more or less like that:
```
object Event {
  def apply[E](payload: E)(implicit serializer: JsonValueCodec[E]): Event = {
    Event(someIdGenerator(), now(), Payload(writeToArray(payload)) 
  }
}
```

I though I would be able to create a custom codec for Payload, that would directly write my already jsonified content, but it appears I can't.
The method does exist (writeNonEscapedAsciiStringWithoutParentheses) but is private.
Neither can I do some jsonWriter.writeBytes with a byte Array.

Is there some simple way to achieve this without adding a new method or making 'writeNonEscapedAsciiStringWithoutParentheses' public ?

Thank you,

Camille

**Comment by plokhotnyuk** [comment]
Could you, please, give an expected example of JSON?

**Comment by plokhotnyuk** [comment]
@cchafer v0.51.0 have new methods that can be used in custom codecs for that

please, check how it works for reading and writing of raw values [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/2a6798ba44cb9fa5d05e1cdb18c06d621dab449f/jsoniter-scala-macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L551-L580) - possible it suits your use case too

**Comment by cchafer** [comment]
Hi, and sorry for the delay.
Added methods are exactly what I missed before !  (hence closing issue)

Thank you so much,

Camille
