### ISSUE TITLE
No implicit 'com.github.plokhotnyuk.jsoniter_scala.core.JsonValueCodec[_]' defined for 'Any'

### ISSUE THREAD

**Issue by yinchuanwang** [plokhotnyuk/jsoniter-scala#264]
当case class里面有Any类型时，或者Map的值是any类型时，编译会报错。

```
case class GenericMetric(timestamp: Long, metric: String, value: Any, tags: Map[String, String])

implicit val codec: JsonValueCodec[GenericMetric] = JsonCodecMaker.make[GenericMetric](CodecMakerConfig())
```

或者

```
case class GenericMetric(timestamp: Long, metric: String, value: Double, tags: Map[String, Any])
implicit val codec: JsonValueCodec[GenericMetric] = JsonCodecMaker.make[GenericMetric](CodecMakerConfig())

```

**Comment by plokhotnyuk** [comment]
Jsoniter-scala doesn't support derivation of codecs for `Any`.

And it will not do this also because of [security reasons](https://github.com/FasterXML/jackson-databind/issues/2258).

So, you can use generic types or/and custom codecs for this case.

**Comment by yinchuanwang** [comment]
谢谢，上面的方案能解决一部分问题。不过像Map[String, T] 这种类型，经常遇到的情况是值会是多种类型，例如有可能是int, double甚至string类型，例如像下面这种样子的json，这种情况下就没法简单用范型来解决，请问面对这种，目前支持？
```
{
    "timestamp" : 121212,
    "metric" : "cpu",
    "value" : 0.1,
    "tags" : {
          "ip" : "192.168.1.1",
          "status" : 1
     }
}
```

**Comment by plokhotnyuk** [comment]
If you have just `String` and `Int` types for map values than instead of `Any` you can use `Either[String, Int]` a custom codec like [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/a458b41ab64c69e515d9d9554a1fc6609fe187d2/jsoniter-scala-macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L423-L440).

**Comment by yinchuanwang** [comment]
Got it. Thanks for help/

**Comment by DongchaoXu** [comment]
@plokhotnyuk Following this question, I am trying Either[String, Int] with the custom codec [here](https://github.com/plokhotnyuk/jsoniter-scala/blob/a458b41ab64c69e515d9d9554a1fc6609fe187d2/jsoniter-scala-macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L423-L440). While I got the CodecConfigurationException: Can't find a codec for class scala.util.Left. Thank you.
