### ISSUE TITLE
 Scala Native support

### ISSUE THREAD

**Issue by david-bouyssie** [plokhotnyuk/jsoniter-scala#281]
In the readme you say that Scala Native support is not a current goal.
I would like to discuss the current blocking points for this specific support.
I can see that you jsoniter-scala depends on scala-reflect, but it doesn't seem to be used a lot in the library. I only found a Streamable type use in the source code.
Do you know any other issue which could be major blocker?

**Comment by plokhotnyuk** [comment]
Hi, David!

Thanks for the question!

I never tried to compile `jsoniter-scala` modules with `scala-native`.
So any, even failed, attempt will be greatly apretiated.

Also, please consider other options, like:
https://medium.com/@komamitsu/how-to-create-a-shared-library-from-java-code-2273b5015689

**Comment by david-bouyssie** [comment]
Yes I have seen this GraalVM feature. But it's not unobstrusive since it requires some specific Java wrappers on the JVM side.
And regarding performance I think it won't be as good as a pure Scala Native port.

I will try thus to compile your code. I was surprised to see how compact the code is. If I understood correctly there are only 4 scala files to compile from the core folder (if I exclude the tests and examples). Did I miss something?

**Comment by plokhotnyuk** [comment]
Yes, Core API contains only 4 Scala files. But all instances of codecs are generated by the [`make`](https://github.com/plokhotnyuk/jsoniter-scala/tree/master/jsoniter-scala-macros/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros) macro from the `jsoniter-scala-macros` module.

**Comment by ekrich** [comment]
Hi, Scala Native has released `0.4.0` with 2.12, 2.12, and 2.13 support. It might be worth taking a look at supporting now.

**Comment by plokhotnyuk** [comment]
@ekrich I see that you've added support of Scala Native 0.4.0 for scala-collection-compat that is used for testing here. Thank you so much! 

Also, support of Scala Native 0.4.0 was merged in scala-test and scala-check. I'm waiting for their releases with impatience.

Now looking for some benchmark harness that will be able to store results in JMH format...

**Comment by ekrich** [comment]
@plokhotnyuk Scala Test released `3.2.4-M1` for Scala Native support. It looks like Scala Check has been merged but not released.

**Comment by plokhotnyuk** [comment]
@ekrich Here is my 1st attempt: https://github.com/plokhotnyuk/jsoniter-scala/pull/640

Currently sjavatime has missing implementation for some `java.time._` classes https://github.com/ekrich/sjavatime/issues/7 .

Should live with that or it is better to wait for SN support in scala-java-time https://github.com/cquiroz/scala-java-time/issues/45 ?

**Comment by ekrich** [comment]
If there is not too much we could copy from `cquiroz` tree but otherwise it might be wise to wait. I am not opposed to a more lightweight version without all the `Locale` related stuff which could be a good niche for the library.

**Comment by ekrich** [comment]
Were the added classes on the native platform due to missing `nio` or something?

**Comment by plokhotnyuk** [comment]
@ekrich Erik, thank you for the support! 

I am leaning towards the idea of using the same library for both Scala.js and Scala Native versions and `cquiroz/scala-java-time` looks more attractive due support of more types for dates.

Also, I don't understand your last question about missing `nio` or something. Could you please elaborate more or give some examples?

**Comment by ekrich** [comment]
@plokhotnyuk I left the comment on the PR.
