### ISSUE TITLE
Add ability to serialize fields with null or empty containers

### ISSUE THREAD

**Issue by plokhotnyuk** [plokhotnyuk/jsoniter-scala#30]
Currently fields of some option, array or collection types are not serialized for more concise output if their values are null or empty. 
But some JSON APIs require existence of fields for any values including null or empty array, so need to add configuration option for code generation (and a field annotation) to allow altering of this behavior.

**Comment by plokhotnyuk** [comment]
Current w/a are:
- use Option wrapper for collections to serialize Some(Nil) as `[]` in JSON 
- use custom codecs, creation of which can be automated by turning on scalac options to print generated sources: `scalaOptions += "-Xmacro-settings:print-codecs"`

**Comment by nilskp** [comment]
Any chance of getting a configuration option for this anytime soon? I'm having to hack my way around this.

**Comment by nilskp** [comment]
Would it be possible to get a distinction between optional values and arrays?
Generally I'd prefer to have arrays always present, as empty if empty, but leave out optional fields.
This simplifies the code needing to process a JSON output.

**Comment by plokhotnyuk** [comment]
I have already promouted v0.40.0 release to the Maven Central with this commit.

Am I right understand that it will be enough to split current `transientEmpty` on two options:
1) `transientNone` - for options
2) `transientEmpty` -  for any collections which can have different representation (JSON objects for maps or JSON arrays for arrays and other Scala collections)?

**Comment by nilskp** [comment]
For my purposes, right now, yes.

**Comment by plokhotnyuk** [comment]
Nils, v0.41.0 with the commit above is already landed at the Maven Central:
http://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-macros_2.12/0.41.0/

**Comment by nilskp** [comment]
Nice. I'll give it a spin on Monday.
