### ISSUE TITLE
Possibility to read raw JSON

### ISSUE THREAD

**Issue by mindartyr** [plokhotnyuk/jsoniter-scala#306]
Hi, I have a small question:

Is there a possibility to parse the following JSON to the following case class?

```{"param1": 1, "param2": "test", "payload": {"param3": "test", "json": {"param4": 1}}, "param4: "test"}```

```case class Test(param1: Int, param2: String, payload: String)```

**Comment by plokhotnyuk** [comment]
@mindartyr which value should be stored in the `payload` field for the provided input?

**Comment by mindartyr** [comment]
@plokhotnyuk 
In this case: ```{"param3": "test", "json": {"param4": 1}}```. Don't care much if it is a String or Byte array.
Sorry for stupid question, I've tried to look into the library but didn't find this functionality.

**Comment by plokhotnyuk** [comment]
@mindartyr Am I right understand that skipping of this value is not an option?
If yes, then, please, explain why do you need it in the `payload` field and how are you going to use it...

**Comment by mindartyr** [comment]
@plokhotnyuk This is usual case when you need to use the field like `payload`, but leave it untouched (to save it to database for example, as history). 
Problem here that you don't know the structure and types of the JSON inside this field, so you can't map it to the case class.

**Comment by plokhotnyuk** [comment]
@mindartyr please check out if proposed changes suit your needs: https://github.com/plokhotnyuk/jsoniter-scala/pull/307/files

**Comment by mindartyr** [comment]
@plokhotnyuk It seems good, thank you a lot!

**Comment by plokhotnyuk** [comment]
@mindartyr now you can try it using [the latest release](https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v0.51.0)

**Comment by n3ziniuka5** [comment]
I was also looking for this functionality. I ended up copying the `RawVal` from that PR. Perhaps it would make sense to include it in a production package?

The reason I needed it was because I had to deal with the following json:
```
{
  "type": "..",
  "payload": {}
}
```
There are more fields, but I only left the relevant bits. I need to read the `type` field and then read `payload` with appropriate codec based on `type`.

I know I could have used ADT, but that would have required me to used a sealed trait and put all available type definitions in a single file which can get bloated. I prefer to use `MessageEnvelope[MessageType]` kind of structure. With the latest PR I first parse to `MessageEnvelope[RawVal]` and then I separately parse the raw value. Let me know if there are better ways to do this.

**Comment by plokhotnyuk** [comment]
@n3ziniuka5 could you please open a separate ticket with code samples for your data structures?

I think that it is possible to write a custom codec which can do it without parsing to raw bytes.

**Comment by mindartyr** [comment]
Hi @plokhotnyuk 

I am currently struggling with parsing following case class:

```
case class SeqOfRawVal(bs: Seq[Array[Byte]])
```

so basically I want to parse string like 

```
[{"key1": "val2"}, {"key1": "val2"}]
```

to 
```
Seq({"key1": "val2"}, {"key1": "val2"}): Seq[Array[Byte]])
```

Idea is the same as I raised in the beginning, but now I want to have a sequence of raw JSONs.
Do you think this is possible to create a codec using current functionality?

**Comment by plokhotnyuk** [comment]
@mindartyr you can use the following codec for `Seq[Array[Byte]]` like here:
```
object Example01 {
  implicit val seqOfRawValCodec: JsonValueCodec[Seq[Array[Byte]]] = {
    implicit val rawValCodec: JsonValueCodec[Array[Byte]] = new JsonValueCodec[Array[Byte]] {
      override def decodeValue(in: JsonReader, default: Array[Byte]): Array[Byte] = in.readRawValAsBytes()

      override def encodeValue(x: Array[Byte], out: JsonWriter): Unit = out.writeRawVal(x)

      override val nullValue: Array[Byte] = new Array[Byte](0)
    }

    JsonCodecMaker.make[Seq[Array[Byte]]](CodecMakerConfig())
  }

  def main(args: Array[String]): Unit = {
    val data = readFromArray("""[{"key1": "val2"}, {"key1": "val2"}]""".getBytes("UTF-8"))
    val json = writeToArray(data)

    println(data)
    println(new String(json, "UTF-8"))
  }
}
```

**Comment by mindartyr** [comment]
@plokhotnyuk thanks a lot! Will try
