### ISSUE TITLE
[bug] Custom codec for `Option[A]` is used during decoding but not during encoding

### ISSUE THREAD

**Issue by atais** [plokhotnyuk/jsoniter-scala#392]
I think the case is best showcased with this little scenario:

```
object CustomOptionEncoderSpec extends App {

  case class Bar(a: String)

  case class Foo(a: Bar, b: Option[Bar])

  implicit val barCodec: JsonValueCodec[Bar] = JsonCodecMaker.make[Bar](CodecMakerConfig())

  implicit val optionBarCodec: JsonValueCodec[Option[Bar]] = new JsonValueCodec[Option[Bar]] {
    override def decodeValue(in: JsonReader, default: Option[Bar]): Option[Bar] = {
      val d = barCodec.decodeValue(in, barCodec.nullValue)
      Option(d).map(_.copy("read between the lines"))
    }

    override def encodeValue(x: Option[Bar], out: JsonWriter): Unit =
      out.writeVal("Nothing for you!")

    override def nullValue: Option[Bar] = None
  }

  implicit val fooCodec: JsonValueCodec[Foo] = JsonCodecMaker.make[Foo](CodecMakerConfig())

  val test1 = Foo(Bar("a"), Some(Bar("b")))
  val test2 = Foo(Bar("a"), None)

  println(writeToString(test1))
  println(writeToString(test2))

  println(readFromString[Foo]("{\"a\":{\"a\":\"a\"},\"b\":{\"a\":\"b\"}}"))
  println(readFromString[Foo]("{\"a\":{\"a\":\"a\"}}"))

}
```

Generally, `Option[Bar]` codec has been modified, so it does not encode or decode what is actually given. 
When decoding it changes the text to "read between the lines"
While encoding it should always change the text to "Nothing for you".

Nice and easy but printing the result shows that encoding always uses the default `Codec` for `Foo` not the one for `Option[Foo]`. I think this is a bug.

```
{"a":{"a":"a"},"b":{"a":"b"}}
{"a":{"a":"a"}}
Foo(Bar(a),Some(Bar(read between the lines)))
Foo(Bar(a),None)
```

**Comment by plokhotnyuk** [comment]
It is not a bug, but a feature. 

To enforce serialization of optional fields for `Foo` please use `JsonCodecMaker.make[Foo](CodecMakerConfig(transientNone = false))`

**Comment by atais** [comment]
Thanks!

**Comment by plokhotnyuk** [comment]
You are welcome!

There are no magic - just turn on printing of generated code to see what is happening under hood: https://github.com/plokhotnyuk/jsoniter-scala/blob/c3abc3908fb9dd9f160b9edcc2ef3859883850f9/jsoniter-scala-examples/build.sbt#L4

**Comment by atais** [comment]
I knew which codec is used but I did not know why :)
