### ISSUE TITLE
writeRawVal and readRawValAsBytes methods don't work as expected

### ISSUE THREAD

**Issue by mindartyr** [plokhotnyuk/jsoniter-scala#401]
This test case fails on both asserts  with:
```
[info] TestJsonIter:
[info] - parsing *** FAILED ***
[info]   "[ ]{"test_props": 1}" did not equal "[]{"test_props": 1}"
```

```
[info] TestJsonIter:
[info] - parsing *** FAILED ***
[info]   "{"val1":[ "test", "val2": "test", "props": {"test_props": 1}, "val3": ]3}" did not equal "{"val1":["test","val2":"test","props": {"test_props": 1}"val3":]3}"
```

```
import com.github.plokhotnyuk.jsoniter_scala.core.{JsonReader, JsonValueCodec, JsonWriter, readFromArray, writeToArray}
import com.github.plokhotnyuk.jsoniter_scala.macros.{CodecMakerConfig, JsonCodecMaker}
import com.typesafe.scalalogging.StrictLogging
import org.scalatest.FunSuite

case class TestClass(val1: String,
                     val2: String,
                     props: Array[Byte],
                     val3: Int)


class TestJsonIter  extends FunSuite with StrictLogging {

    test("parsing") {
        val testJson = """{"val1": "test", "val2": "test", "props": {"test_props": 1}, "val3": 3}"""
        val data = readFromArray(testJson.getBytes("UTF-8"))(TestClass.codec)
        val json = writeToArray(data)(TestClass.codec)

        assert(new String(data.props, "UTF-8") == """{"test_props": 1}""")
        assert(testJson == new String(json, "UTF-8"))
    }
}

object TestClass {
    implicit val codec: JsonValueCodec[TestClass] = {

        implicit val rawValCodec: JsonValueCodec[Array[Byte]] = new JsonValueCodec[Array[Byte]] {
            override def decodeValue(in: JsonReader, default: Array[Byte]): Array[Byte] = in.readRawValAsBytes()

            override def encodeValue(x: Array[Byte], out: JsonWriter): Unit = out.writeRawVal(x)

            override val nullValue: Array[Byte] = new Array[Byte](0)
        }

        JsonCodecMaker.make[TestClass](CodecMakerConfig())

    }
}
```

So there is a problem if you use this approach with `Array[Byte]` when encoding and using case classes which are more complex.

Related with https://github.com/plokhotnyuk/jsoniter-scala/issues/306

**Comment by mindartyr** [comment]
Using release `0.55.2`

**Comment by plokhotnyuk** [comment]
@mindartyr It is not a bug.

`readRawValAsBytes` do its job properly by holding all bytes including white spaces.

**Comment by mindartyr** [comment]
@plokhotnyuk I see, thanks. 
And what about `writeRawVal`?

**Comment by plokhotnyuk** [comment]
`writeRawVal` just copies all supplied bytes to output untouched.

**Comment by mindartyr** [comment]
Ok, then I think my problem is that `writeRawVal ` doesn't call `writeOptionalCommaAndIndentionBeforeValue` method, so the `comma` attribute is `false` and there is no comma written after `Array[Byte]` block. 

Do you see that in the example above? If not then I am missing something :) The problem is not only in spaces, but there is comma missing after `"props": {"test_props": 1}` block.

Does it make sense? Is it possible to call `writeOptionalCommaAndIndentionBeforeValue` in `writeRawVal`?

**Comment by plokhotnyuk** [comment]
> The problem is not only in spaces, but there is comma missing after `"props": {"test_props": 1}` block.

Nice spot! It is a bug in the `writeRawVal` implementation.

**Comment by plokhotnyuk** [comment]
@mindartyr thank you for the bug report!

Now cutting a release with the fix for it.

**Comment by mindartyr** [comment]
@plokhotnyuk thanks for a quick fix! Will wait for release 👍

**Comment by plokhotnyuk** [comment]
Done: 
https://github.com/plokhotnyuk/jsoniter-scala/releases/tag/v0.55.4

It is already available from the Sonatype staging repo:
https://oss.sonatype.org/content/repositories/staging/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-macros_2.13/0.55.4/

...and should be downloadable from the Maven Central in an hour here:
http://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-macros_2.13/
