### ISSUE TITLE
Disable auto codec generation

### ISSUE THREAD

**Issue by shmishleniy** [plokhotnyuk/jsoniter-scala#405]
Hi,

I don't find such feature here
https://github.com/plokhotnyuk/jsoniter-scala/blob/6bd2a658f30171b828139df6635c93511688442f/jsoniter-scala-macros/src/main/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala#L1352
So the question/proposition.

what do you think about the feature to disable auto code generation for all(except scala default)/some of types?

It can be useful to make 100% sure that used provided implicit codec and protect you from accidentally move/delete/lost implicit codec somehow. Currently you cannot be sure that used provided implicit codec.

**Comment by plokhotnyuk** [comment]
The main idea of auto generation is to minimize overhead in compile and run-time.

If you unsure about which codecs were injected by implicits you can turn on printing of generated codecs to ensure that all is right if your tests cannot show you that.

**Comment by shmishleniy** [comment]
Thanks, for response.
I mean for example we import codecs like modelCodecs._ with defined custom codec for type `A` and later someone accidentally remove or move to another place this codec.
For now it can be covered with serialization/deserialization test but not with compiler error.

Is there any significant performance degradation with implicit codecs injection?

Ok, if no planned please close this issue.

**Comment by plokhotnyuk** [comment]
Currently all derived codecs are lightweight in run-time but each implementation of the codec interface used in runtime decreases possibility to optimize megamorphic interface calls.

Derivation of codecs by macros happens in compile time only, so turning on printing of derived codecs will log all of them. Increasing of the `make` macro call increases the compilation time.

If you miss some injection of a custom codec the `make` macro will derive safe defaults. 

To minimize such kind of missing all derivations can be located in a separated file:
```
case class A(i: Int, s: String)
case class B(i: Int, d: Double)
case class C(a: A, b: B)

object Codecs {
   implicit val someCustomCodec = make[A](CodecMakerConfig(<some customization>))
   val rootCodec = make[C](CodecMakerConfig())
}
```
or closely to definition of each case class:
```
case class A(i: Int, s: String)
object A {
   implicit val codec = make[A](CodecMakerConfig(<some customization>))
}
case class B(i: Int, d: Double)
object B {
   implicit val codec = make[B](CodecMakerConfig(<some customization>))
}
case class C(a: A, b: B)
object C {
   implicit val codec = make[C](CodecMakerConfig(<some customization>))
}
```

Please give an example of code for your case if those approaches are not suitable for you.

**Comment by shmishleniy** [comment]
yes the safe way is to keep all the codec together, like

implicit val RecipeCodec: JsonValueCodec[Recipe] = {
  implicit val QuantityTypeCodec: JsonValueCodec[QuantityType] = JsonCodecMaker.make[QuantityType](CodecMakerConfig(discriminatorFieldName = None))
  implicit val UseTypeCodec: JsonValueCodec[UseType] = JsonCodecMaker.make[UseType](CodecMakerConfig(discriminatorFieldName = None))
  JsonCodecMaker.make[Recipe](CodecMakerConfig())
}

because in case of import from somewhere I can't be sure there `api.codecs._` contains codecs for my types

implicit val RecipeCodec: JsonValueCodec[Recipe] = {
  import api.codecs._
  JsonCodecMaker.make[Recipe](CodecMakerConfig())
}
