### ISSUE TITLE
How to map JSON to a case class field with a different name

### ISSUE THREAD

**Issue by programmatix** [plokhotnyuk/jsoniter-scala#422]
Apologies if this is answered elsewhere, I looked through the docs, examples and issues but couldn't find anything, though I suspect it's a common question.

I'm using Jsoniter in the in-development Scala SDK for the NoSQL database Couchbase, and would like to be be able to do the following:

`
    import com.github.plokhotnyuk.jsoniter_scala.macros._
    import com.github.plokhotnyuk.jsoniter_scala.core._

    case class Example(@JsonProperty("Name") name: String)

    object Example {
      implicit val codec: JsonValueCodec[Example] = JsonCodecMaker.make(CodecMakerConfig)
    }

    val json = """{"Name":"test"}"""

    val example = readFromArray[Example](json.getBytes(StandardCharsets.UTF_8))
`
E.g. the JSON contains field "Name" but the case class is "name".
But I hit this error:

`com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: missing required field "name", offset: 0x00000337, buf:`

Is the @JsonProperty Jsoniter annotation not supported?  Is there another way of doing this?

**Comment by plokhotnyuk** [comment]
@programmatix Hi, Graham!

No problem! Opening an issue for questions is allowed here! Also, for fast question you can use [Gitter chat](https://gitter.im/plokhotnyuk/jsoniter-scala).

Jsoniter-scala supports annotation for mapping field names to JSON key but they are not Java or Scala run-time annotation, instead it use Scala compile-time annotations, like here:

```
    case class Example(@named("Name") name: String)
```

If you have no possibility to modify your data model, then you can try a field name mapping function of `CodecMakerConfig` during derivation of the codec:

```
      implicit val codec: JsonValueCodec[Example] = JsonCodecMaker.make(CodecMakerConfig.withFieldNameMapper {
        case "name" => "Name"
      })
```

Also, there are predefined partial function for field name mapping which enforces kebab-case, snake_case, PascalCase, and camelCase. Bellow is usage of one of them for your example:
```
      implicit val codec: JsonValueCodec[Example] =
        JsonCodecMaker.make(CodecMakerConfig.withFieldNameMapper(JsonCodecMaker.EnforcePascalCase))
```

**Comment by programmatix** [comment]
Perfect!  Thanks @plokhotnyuk .
