### ISSUE TITLE
Jsoniter-scala hides compiler errors which are happened during the `make` macro expansion

### ISSUE THREAD

**Issue by plokhotnyuk** [plokhotnyuk/jsoniter-scala#423]

**Comment by alexarchambault** [comment]
@plokhotnyuk Seeing a lot of those on the CI of my projects that started to use jsoniter-scala… Would it be possible to print the exception stack trace, and along with its cause if any and its stack trace too (recursing on the causes)? That could help debugging those.

Almost all the time, the errors I get says
```
Cause:

[error] java.lang.AssertionError: assertion failed: com package com <none>
[error]     JsonCodecMaker.make(CodecMakerConfig)
[error]                        ^
```

**Comment by plokhotnyuk** [comment]
@alexarchambault Hi, Alexandre!

The main cause of such kind of errors is calling of the `make` macro in some deeply nested scope from which it cannot safely evaluate the `CodecMakerConfig` parameter.

Have you tried some of options which are proposed as W/A for the 2nd known issue [here](https://github.com/plokhotnyuk/jsoniter-scala#known-issues)?
