### ISSUE TITLE
Implications of withSetMaxInsertNumber(VeryHighNumber)

### ISSUE THREAD

**Issue by programmatix** [plokhotnyuk/jsoniter-scala#458]
Hi!  I use your excellent library inside the Couchbase Scala SDK, when converting JSON directly to/from a user's case class.  One of our users hit an issue [on our forums](https://forums.couchbase.com/t/scala-sdk-get-does-not-work-when-document-exceeds-a-certain-size/24067), with the error containing "too many set inserts".

After some searching and testing I found I can get by this using withSetMaxInsertNumber, and I'm thinking I may as well set withMapMaxInsertNumber for good measure too.  Are there any negative repercussions I should be aware of from just setting this to, say, 100,000 for both values?  I'd like to prioritise an easy out-of-the-box experience for users.

**Comment by plokhotnyuk** [comment]
Big values for this configuration option can affect users which will use the generated codec for parsing of _untrusted_ input because it opens [DoS/DoW vulnerabilities of Scala's `HashMap`/`HashSet` implementations](https://github.com/scala/bug/issues/11203).

But for cases of trusted input big limits are acceptable.

**Comment by programmatix** [comment]
Thanks @plokhotnyuk, appreciate your response, and for the background.  I'd expect users to be doing basic data validation before putting raw input JSON into the database, plus there's a per-document limit of 20mb.  And situations where raw json from an untrusted source are put directly into the database would be rare, I would think.  So I don't think it will be an issue in practice.   I'll leave it as the 100,000 I've set the config values too, and consider whether I should document this somewhere as a caveat.
