### ISSUE TITLE
scala default annotation `@transient` shall be treated the same way as jsoniter's annotation

### ISSUE THREAD

**Issue by b-gyula** [plokhotnyuk/jsoniter-scala#484]
There is already a `@transient` annotation in scala. That could be treated the same way as jsoniter's own `@transient` annotation

**Comment by plokhotnyuk** [comment]
Using of own annotation was intentional to avoid possible mismatch with semantic of Scala's one or peculiarities of their usage.

**Comment by b-gyula** [comment]
Thanks for the answer!
I believe they are use for the same purpose much more than 50% of the cases, so just identify those rare cases might be more developer friendly. E.g. 
```scala
@transient
@com.github.plokhotnyuk.jsoniter_scala.macros.transient(false)
```
Anyway thanks!
