### ISSUE TITLE
List[T] is serialized without commas

### ISSUE THREAD

**Issue by lebel-louisjacob** [plokhotnyuk/jsoniter-scala#488]
I'm trying to parse `List[T]`s. I tried:
```scala
implicit val seqCodec: JsonValueCodec[List[Int]] =
    JsonCodecMaker.make(CodecMakerConfig)

Console.out.write(writeToArray(List(1, 2, 3, 4, 5)))
```

But this yields:
```log
[12345]
```

I was expecting commas to separate each number, i.e.
```log
[1,2,3,4,5]
```

but they were instead all glued together. What did I do wrong?

**Comment by plokhotnyuk** [comment]
Cannot reproduce it using a simple example from the following PR: https://github.com/plokhotnyuk/jsoniter-scala/pull/489

Please ensure that no other imported methods or values are in scope for the reported code.

Which version of JDK and Scala do you use for that?

**Comment by lebel-louisjacob** [comment]
@plokhotnyuk Yeah, I should have added these info first I guess. Here's the dependencies from my project's `pom.xml` (under maven):
```xml
<dependencies>
  ...
  <dependency>
    <groupId>com.github.plokhotnyuk.jsoniter-scala</groupId>
    <artifactId>core_2.12</artifactId>
    <version>0.28.1</version>
  </dependency>
  <dependency>
    <groupId>com.github.plokhotnyuk.jsoniter-scala</groupId>
    <artifactId>jsoniter-scala-macros_2.12</artifactId>
    <version>2.1.8</version>
    <scope>provided</scope>
  </dependency>
</dependencies>
```
I'm using `Scala 2.12.8` with `JDK 11`.

Weird enough that it works on your side, I actually dragged and dropped your code and replaced the entire `main` function without success. Currently cloning to cleanly try your code on my setup.

For now, as a workaround, I built my own general `JsonValueCodec[List[A]]` (for any `A` with a `JsonValueCodec`) implementation and instantiated it with `A` = `MyType` instead of the native version `jsoniter` provides. [This](https://gitlab.com/exo-language/scala-compiler/-/blob/2.0.0/ast/src/main/scala/com/github/louisjl/exo/constructs/Expression.scala#L25) is actually my code (with only `encodeValue` implemented).

As far as I know, many implicit values for the same `JsonValueCodec[List[A]]` would throw a compile time error (since `Scala` renders many implicit candidates as ambiguous). Because I have at least my implementation available where I serialize ADTs, I think the problem lies somewhere else.

**Comment by lebel-louisjacob** [comment]
To be honest, I have no clue how to run your code on my setup x)
I would appreciate if you could tell me how to run your example on my machine.

If trying my code wouldn't bother you, then I just created an [ultra minimal branch](https://gitlab.com/exo-language/scala-compiler/-/blob/test-jsoniter/src/main/scala/com/github/louisjl/exo/cli/App.scala) on my repository with pretty much only the code in `Example01.scala` on #448.

If you've got Intellij, you only have to clone and click play on the left of the main function.

**Comment by plokhotnyuk** [comment]
The problem is that you mixed binary uncompatible versions of jsoniter-scala.
Please fix your dependencies use artifacts of the same release:
```
<dependencies>
  ...
  <dependency>
    <groupId>com.github.plokhotnyuk.jsoniter-scala</groupId>
    <artifactId>jsoniter-scala-core_2.12</artifactId>
    <version>2.1.8</version>
  </dependency>
  <dependency>
    <groupId>com.github.plokhotnyuk.jsoniter-scala</groupId>
    <artifactId>jsoniter-scala-macros_2.12</artifactId>
    <version>2.1.8</version>
    <scope>provided</scope>
  </dependency>
</dependencies>
```

**Comment by lebel-louisjacob** [comment]
Alright, modifying my `pom.xml` dependencies fixed the issue. Thanks for your fast responses.
