### ISSUE TITLE
Consider support of binary JSON representations: CBOR, MessagePack and UBJSON

### ISSUE THREAD

**Issue by plokhotnyuk** [plokhotnyuk/jsoniter-scala#59]

**Comment by plokhotnyuk** [comment]
Use:
- [borer](https://github.com/sirthias/borer) or [jackson-dataformats-binary](https://github.com/FasterXML/jackson-dataformats-binary/tree/master/cbor) libraries for CBOR 
- [uPickle](https://github.com/lihaoyi/upickle) for MessagePack support

**Comment by nilskp** [comment]
Would be nice to have CBOR support. I currently am looking at Borer, and it's just a pain to have two libraries, since I need to support both JSON and CBOR.
