### ISSUE TITLE
add simdjson to the benchmark

### ISSUE THREAD

**Issue by LifeIsStrange** [plokhotnyuk/jsoniter-scala#649]
simdjson is probably the fastest json library on earth, jsoniter-scala might be the second fastest!
It would be nice to add it to the benchmark :)
As there are no simdjson java binding currently, it should run using either C++ or Rust.

**Comment by plokhotnyuk** [comment]
AFAIK simdjson doesn't parse to the arbitrary data structures. Even if it would do that C++/Rust data structures will differ greatly from those which exists in Scala.

**Comment by LifeIsStrange** [comment]
And what about rapidjson?

**Comment by plokhotnyuk** [comment]
Please see p.2 above

**Comment by yarosman** [comment]
https://github.com/simdjson/simdjson-java?tab=readme-ov-file#512-bit-vectors
