### ISSUE TITLE
This recent port of Lemire's Double parser is 5.5X faster than the default double parser

### ISSUE THREAD

**Issue by LifeIsStrange** [plokhotnyuk/jsoniter-scala#672]
https://github.com/wrandelshofer/FastDoubleParser
(if the microbenchmark generalize)
I wonder how jsoniter-scala performs against the double parser baseline on this benchmark. I also wonder if you could reuse the same implementation or integrate/combine some of your optimizations with their.

see also the original paper https://arxiv.org/abs/2101.11408

exciting times @plokhotnyuk :)

**Comment by plokhotnyuk** [comment]
@LifeIsStrange Thanks a lot for your interest and support!

This library is already using fast and middle path algorithms for parsing of float and double values.

I'm going to create a benchmark to compare it with https://github.com/wrandelshofer/FastDoubleParser

The remaining part is the slow path for values which are close to near-halfway values: https://github.com/plokhotnyuk/jsoniter-scala/issues/237

**Comment by plokhotnyuk** [comment]
@LifeIsStrange Here are results of `String` parsing with FastDoubleParser comparing with `java.lang.Double.parseDouble` and jsoniter-scala: https://github.com/plokhotnyuk/jsoniter-scala/pull/746

**Comment by plokhotnyuk** [comment]
@LifeIsStrange Here are results of `ArrayOfDoublesReading` and `ArrayOfFloatsReading` benchmarks for a snapshot version of Jackson with adopted FastDoubleParser implementation for doubles and floats on Intel® Core™ i9-11900H CPU @ 2.5GHz (max 4.9GHz):

```
[info] Benchmark                            (size)   Mode  Cnt       Score      Error  Units
[info] ArrayOfDoublesReading.jacksonScala      128  thrpt   25  108432.497 ± 2682.725  ops/s
[info] ArrayOfDoublesReading.jsoniterScala     128  thrpt   25  380911.318 ± 9153.106  ops/s
[info] ArrayOfFloatsReading.jacksonScala       128  thrpt   25  140210.525 ± 4172.061  ops/s
[info] ArrayOfFloatsReading.jsoniterScala      128  thrpt   25  508397.043 ± 7721.395  ops/s
```

**Comment by LifeIsStrange** [comment]
Thanks @plokhotnyuk :)
