### ISSUE TITLE
Add parsing of numeric scala Enumerations

### ISSUE THREAD

**Issue by cchafer** [plokhotnyuk/jsoniter-scala#678]
Scala enumerations are handled out of the box, but when using 'id only' enumerations (ie without names), I would expect jsoniter to handle it as an integer constant.

In the following example:
```
final case class Test(e: Test.SomeEnum)

object Test {
  type SomeEnum = SomeEnum.Value

  object SomeEnum extends Enumeration {
    val One = Value(1)
    val Two = Value(2)
  }

}

implicit val codec: JsonValueCodec[Test] = JsonCodecMaker.make

val jsonWithInt = """{"e": 1}"""
readFromArray(jsonWithInt.getBytes) // JsonReaderException: expected '"', offset: 0x00000006

val jsonWithString = """{"e": "1"}"""
readFromArray(jsonWithString.getBytes) // JsonReaderException: illegal enum value "1"

```

First try to unserialize the enum value as an int, indicates that a quote is needed, and second try, with a string, throws, because the string value of the enumeration is not "1", but "One".

Did I miss any option, is it something no-one ever needed, or is it a bug ?

Thank you !

Camille

**Comment by plokhotnyuk** [comment]
@cchafer Hi, Camille!

Thanks for your feedback!

Please pick the 2.7.0 version and use `make(CodecMakerConfig.withUseScalaEnumValueId(true))` to derive codecs which parse and serialize Scala enumerations as id numbers.
