### ISSUE TITLE
Issue with maven build: ReificationSupport fails

### ISSUE THREAD

**Issue by david-bouyssie** [plokhotnyuk/jsoniter-scala#689]
Hi there,

I have an issue with a maven build (net.alchim31.maven : scala-maven-plugin) leading to this error:
```
 exception during macro expansion:
java.lang.IllegalArgumentException: can't flatten val x = Seq.newBuilder[Long]
        at scala.reflect.internal.ReificationSupport$ReificationSupportImpl.toStats(ReificationSupport.scala:100)
```
The case class I want to deserialize is like this:
```case class Task(projectId: Long, jobIds: Seq[Long])```

I don't have any issue with my SBT build.

**Comment by plokhotnyuk** [comment]
@david-bouyssie David, thanks for the bug report! For which version of Scala the compilation error throws? Do you have the ability to prepare some minimal project which reproduces it?

I've found similar errors in bug reports for scalac: https://github.com/scala/bug/issues/8609
I'm going to find some workaround but need to reproduce the error first.

**Comment by david-bouyssie** [comment]
Sorry I missed that information.
Used Scala Version is 2.11.11

So might be a scalac issue?

I can try to make a sample project.

**Comment by david-bouyssie** [comment]
This is really weird, I can't reproduce it in a simple Sandbox.
I hope I can isolate the problem but it may take some time.

**Comment by plokhotnyuk** [comment]
@plokhotnyuk David, could you please build SNAPSHOT verison for changes in the following PR and check if they work for you: https://github.com/plokhotnyuk/jsoniter-scala/pull/692

**Comment by david-bouyssie** [comment]
Oh nice, you find a workaround!
Yes I'll do that later.

**Comment by david-bouyssie** [comment]
It looks good to me with this fix.

Thanks a lot!

**Comment by plokhotnyuk** [comment]
@david-bouyssie Thank you too for your help and support!

Please peek the v2.7.2 release with the fix.

**Comment by david-bouyssie** [comment]
Amazing, thanks again for your reactivity!
