### ISSUE TITLE
Reading large file containing JSON objects on each line lazily

### ISSUE THREAD

**Issue by steven-lai** [plokhotnyuk/jsoniter-scala#703]
I have a large (multiple GBs) file which contains a single JSON object on each line in UTF-8 encoding (just sampled my data they seem to be about 400-700 UTF-8 characters per line).

I'd like to lazily read the file (e.g. iterator) instead of one shot - I have what I believe a solution for that (see below).
```
// Simplified JsonEvent
case class JsonEvent(id: String, eventType: String, time: Long, optionalField: Option[String], varLengthFieldA: Option[List[String]], varLengthFieldB: Map[String, String])

implicit val jsonEventCodec: JsonValueCodec[JsonEvent] = JsonCodecMaker.make(
  CodecMakerConfig
    .withFieldNameMapper(JsonCodecMaker.enforce_snake_case))
val gzipInputStreamBufferSize = 8388608
val inputStreamBufferSize = 8388608
val blockingQueueSize = 100000
var eventConsumedCount = 0L
val jsoniterCharBufSize = 4096
val jsoniterBufSize = 8388608 // Half this seems to be relatively the same performance
// I'm reading a gzipped file from HDFS but opening a file should be the same
val inputStream = hdfsFS.open(new Path(file), inputStreamBufferSize)
val gzipInputStream = new GZIPInputStream(inputStream, gzipInputStreamBufferSize)
// Fixed size so we don't OOM
val blockingQueue = new ArrayBlockingQueue[JsonEvent](blockingQueueSize)
val producerThread = new Thread(new Runnable {
  override def run(): Unit = {

    scanJsonValuesFromStream(
      gzipInputStream,
      ReaderConfig
        .withCheckForEndOfInput(false)
        .withPreferredCharBufSize(jsoniterCharBufSize)
        .withPreferredBufSize(jsoniterBufSize)) {

      (jsonValue: JsonEvent) =>
        try {
          blockingQueue.put(jsonValue)
        } catch {
          case _: InterruptedException => /* DO NOTHING */
        }
        true
    }(jsonEventCodec)
  }
})

producerThread.start()
while (producerThread.isAlive || !blockingQueue.isEmpty) {
  // Do something meaningful with it, currently just counting the events
  Option(blockingQueue.poll(waitMs, TimeUnit.MILLISECONDS)).foreach(_ => eventConsumedCount += 1)
}
```

Currently, I don't believe I can:
```
readFromStream(inputStream, ReaderConfig.withCheckForEndOfInput(false))
readFromStream(inputStream, ReaderConfig.withCheckForEndOfInput(false)) // Doesn't read the "2nd line"
```

With Jackson, I can do something like:
```
val objectMapper = ???
val gzipInputStreamBufferSize = 8388608
val inputStreamBufferSize = 8388608
val jsonFactory = new JsonFactory(objectMapper)
// I'm reading a gzipped file from HDFS but opening a file should be the same
val inputStream = hdfsFS.open(new Path(file), inputStreamBufferSize)
val gzipInputStream = new GZIPInputStream(inputStream, gzipInputStreamBufferSize)
val jsonParser: JsonParser = jsonFactory.createParser(gzipInputStream)
while (jsonParser.nextToken() != null) {
  val jsonEvent = objectMapper.parse[JsonEvent](jsonParser)
  ...
}
```
This seems to perform better (just in terms of pure raw performance, didn't look at memory). I'm getting about 120 event/ms with Jackson and about 105 event/ms with Jsoniter in my test env (this is averaged results from 20 iterations). I'm still running more tests tweaking the buffer sizes. Open to any suggestions you may have about improving the process.

EDIT: It's pretty likely the blocking queue logic is adding some performance penalty here.
EDIT: `blockingQueueSize` of size ~5 seems big enough to not throttle the `put`

**Comment by plokhotnyuk** [comment]
@steven-lai Hi, Steven! Why do you scan in a separated thread? Have you tried handling of parsed events in the same thread?

**Comment by steven-lai** [comment]
Ah, you are absolutely correct, so let's disregard the performance for now (I re-ran without the blocking queue stuff and was able to get 125 event/ms). So how can I effectively parse line by line from an `InputStream`?

**Comment by plokhotnyuk** [comment]
> So how can I effectively parse line by line from an `InputStream`?

Use `scanJsonValuesFromStream` with the `ReaderConfig` value that have properly tuned `preferredBufSize` and `preferredCharBufSize` for max length of the serialized event in bytes and max string length in parsed events accordingly.

Do you have possibility to share your benchmarks with input samples?

**Comment by steven-lai** [comment]
Sorry, I got side-tracked, the following is Jsoniter's equivalent that I'm trying to find:

```
val objectMapper = ???
val inputStream = ???
val jsonFactory: JsonFactory = new JsonFactory(objectMapper)
val jsonParser = jsonFactory.createParser(inputStream)

// Wrap the parsing logic into an iterator/stream
val iter = Iterator
      .continually(objectMapper.parse[JsonEvent](jsonParser))
      .takeWhile(_ => jsonParser.nextToken() != null)
```

From benchmark side, it's pretty obvious that all the degradation has been logic I added (see blocking queue)

**Comment by plokhotnyuk** [comment]
The Core API is concise and does not extract parser (`JsonReader`) instances to users for safety and simplicity of usage. The `scanJsonValuesFromStream` call manages thread-local instances of the internal parser with buffers. Buffers are growable and the internal parser maintains their size to not exceed configured limits after return from the `scanJsonValuesFromStream` call.

**Comment by steven-lai** [comment]
Thanks, would it be feasible/reasonable to request that as a feature for future enhancement?

**Comment by plokhotnyuk** [comment]
@steven-lai Steven, would adding of following methods to the `core` package object match your needs?
```
  def toJsonValuesIteratorFromStream[@specialized A](in: InputStream, config: ReaderConfig)(implicit codec: JsonValueCodec[A]): Iterator[A] = ???

  def toJsonArrayIteratorFromStream[@specialized A](in: InputStream, config: ReaderConfig)(implicit codec: JsonValueCodec[A]): Iterator[A] = ???
```

As an option I can make `jsoniter_scala` package visibility for the `JsonReader.skipWhitespaces` and then you can create own iterators in some extension package like:
```
package com.github.plokhotnyuk.jsoniter_scala

package object extra {
  def toJsonValuesIteratorFromStream[@specialized A](in: InputStream, config: ReaderConfig)(implicit codec: JsonValueCodec[A]): Iterator[A] = {
    val reader = new JsonReader(
      buf = new Array[Byte](config.preferredBufSize), 
      charBuf = new Array[Char](config.preferredCharBufSize), 
      config = config)
    Iterator
      .continually(codec.decodeValue(reader, codec.nullValue))
      .takeWhile(_ => reader.skipWhitespaces())
  }
  ....
}
```

**Comment by steven-lai** [comment]
I don't have any strong preference on either approach as it looks like it'll both fit my needs.

**Comment by plokhotnyuk** [comment]
@steven-lai Please peek the 2.8.0 version with changes.

**Comment by steven-lai** [comment]
Everything seems to check out. One minor change I had to make was:

```
private[this] var continue: Boolean = reader.skipWhitespaces()
```

Hopefully this is to correct way to account for an empty file. Thanks for adding this functionality!
