### ISSUE TITLE
Please add Automatic-Module-Name to the manifest files

### ISSUE THREAD

**Issue by makingthematrix** [plokhotnyuk/jsoniter-scala#714]
This is to fix the Java/Scala compatibility issue described here: https://github.com/makingthematrix/scala-suffix

I tried to fork the project and make a PR myself but it's huge - I cancelled `git clone` at 12% when it was already 1GB of downloaded data. Maybe I'm doing something wrong?

Anyway, if you could add in `build.sbt` in respective places for each of the subprojects:
```
packageOptions += Package.ManifestAttributes("Automatic-Module-Name" -> "<subproject name>")
```
So, for example, for `core` this would be 
`packageOptions += Package.ManifestAttributes("Automatic-Module-Name" -> "core")`.

наперед дякую )

**Comment by plokhotnyuk** [comment]
@makingthematrix Hi, Maciej! Thanks for reporting the issue with a solution to solve!

The `gh-pages` branch contains a history of benchmark results, so you can clone faster with using shallow depth for the required branch only: `git clone --depth 1 --branch master`.

**Comment by plokhotnyuk** [comment]
@makingthematrix Please peek the 2.8.0 version with the issue fix.

**Comment by plokhotnyuk** [comment]
@makingthematrix yep, it was too shallow... but with depth 1000 it worked fine to me:
```
andriy@notebook:~/tmp$ git clone --depth 1000 --branch master git@github.com:plokhotnyuk/jsoniter-scala.git
Cloning into 'jsoniter-scala'...
remote: Enumerating objects: 12184, done.
remote: Counting objects: 100% (12184/12184), done.
remote: Compressing objects: 100% (2703/2703), done.
remote: Total 12184 (delta 5203), reused 11620 (delta 4719), pack-reused 0
Receiving objects: 100% (12184/12184), 1.67 MiB | 4.76 MiB/s, done.
Resolving deltas: 100% (5203/5203), done.
andriy@notebook:~/tmp$ cd jsoniter-scala/
andriy@notebook:~/tmp/jsoniter-scala$ sbt
[info] welcome to sbt 1.5.1 (Amazon.com Inc. Java 1.8.0_275)
[info] loading global plugins from /home/andriy/.sbt/1.0/plugins
[info] loading settings for project jsoniter-scala-build from plugins.sbt ...
[info] loading project definition from /home/andriy/tmp/jsoniter-scala/project
[info] loading settings for project jsoniter-scala from build.sbt,release.sbt,version.sbt ...
[info] set current project to jsoniter-scala (in build file:/home/andriy/tmp/jsoniter-scala/)
[info] sbt server started at local:///home/andriy/.sbt/1.0/server/c7a3cc37b7cfb890c1ef/sock
[info] started sbt server
sbt:jsoniter-scala> 
```

**Comment by plokhotnyuk** [comment]
@makingthematrix Have you tried if it works well yet? Is it defined somewhere which characters are allowed for the `"Automatic-Module-Name"`?

Probably a better solution would be using an organization value as a prefix:
```
packageOptions += Package.ManifestAttributes("Automatic-Module-Name" -> s"${organization.value}.${moduleName.value}")
```
