### ISSUE TITLE
Parsing Option[T] at root level doesn't accept 'null'

### ISSUE THREAD

**Issue by borissmidt** [plokhotnyuk/jsoniter-scala#838]
While integrating the jsoniter parser into sttp i came to the issue that `null` makes the parser fail while i expected it to return None for an Option[T] at the root level

snipped: 
```scala
case class Inner(a: Int, b: Boolean, c: String)
implicit def optionDecoder[T:JsonValueCodec] : JsonValueCodec[Option[T]]= JsonCodecMaker.make
readFromString[Option[Inner]]("null") // throws error but i expected to get None back
```

As a workaround i made but i think it is brittle and it will replace all Option codecs which isn't really what i want.
```
implicit def optionDecoder[T:JsonValueCodec] : JsonValueCodec[Option[T]]= new JsonValueCodec[Option[T]] {
      val codec = implicitly[JsonValueCodec[T]]
      override def decodeValue(in: JsonReader, default: Option[T]): Option[T] = {
        in.setMark()
        if (
          in.isNextToken('n'.toByte)
            && in.isNextToken('u'.toByte)
            && in.isNextToken('l'.toByte)
            && in.isNextToken('l'.toByte)
        ) {
          default
        }
        else {
          in.rollbackToMark()
          Some(codec.decodeValue(in, codec.nullValue))
        }
      }

      override def encodeValue(x: Option[T], out: JsonWriter): Unit = x.foreach(codec.encodeValue(_,out))

      override def nullValue: Option[T] = None
    }
```
https://github.com/borissmidt/sttp/blob/ebfa240e3d1e42e7905d6d0a759e05c8abde826d/json/jsoniter/src/test/scala/sttp/client3/ziojson/JsoniterJsonTests.scala

**Comment by borissmidt** [comment]
https://github.com/softwaremill/sttp/pull/1248 
i got the tests to work but it seems a bit brittle
Especially because i cannot 'nest' marks so i cannot fallback on an error in an either parsing to the second parser that easily.
I can assume that this is because we use a limited buffer (16kb) in case of a stream and that you cannot rollback to the start of the parse efficiently.

**Comment by plokhotnyuk** [comment]
Currently, jsoniter-scala-macros API doesn't support derivation with injections for `implicit def` (only `implicit val` are supported).

I've added tests for top-level options [here](https://github.com/plokhotnyuk/jsoniter-scala/commit/f0c629c086c4cde5898cea6d342faf6dc95c42b6).

**Comment by borissmidt** [comment]
Ah good that they don't pick up implicit def then it doesn't break the json encoder.
So was this a bug then? Or do i have to make an the implicit def an implicit val to fix this behavior?

**Comment by borissmidt** [comment]
Oke clear i have to use: 
```scala
implicit val codec: JsonValueCodec[Option[Inner]] = JsonCodecMaker.make
```

**Comment by borissmidt** [comment]
Maybe the implicit def i made in this issue ticket could be added although it only works for root instances?
