### ISSUE TITLE
ArrayIndexOutOfBoundsException thrown when serializing some long BigDecimal numbers

### ISSUE THREAD

**Issue by akilegaspi** [plokhotnyuk/jsoniter-scala#879]
Hello,

I've found a bug in the most recent version that throws an ArrayIndexOutOfBoundsException when using the `writeToArray` function with a `BigDecimal` that has a long remainder with a some pattern (I haven't identified the full pattern but it's not always the case that this happens for long remainders in the `BigDecimal`).

We were using an older version of jsoniter of the current major revision but seems like this is also present on the latest minor version.

Code to reproduce the error:
```scala
import com.github.plokhotnyuk.jsoniter_scala.core._
import com.github.plokhotnyuk.jsoniter_scala.macros._
case class Foo(bar: BigDecimal)
implicit val c: JsonValueCodec[Foo] = JsonCodecMaker.make
val s = readFromArray("""{"bar": 126.09999999999999001}""".getBytes("UTF-8"))
val u = writeToArray(s) // throws exception
```

Exception:

```
  com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.write8Digits(JsonWriter.scala:1604)
  com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.write18Digits(JsonWriter.scala:1612)
  com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeBigDecimalRemainder(JsonWriter.scala:1109)
  com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeBigDecimal(JsonWriter.scala:1102)
  com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeBigDecimal(JsonWriter.scala:1052)
  com.github.plokhotnyuk.jsoniter_scala.core.JsonWriter.writeVal(JsonWriter.scala:246)
  ...
```

Additional:

Affected versions:
`version >= 2.13.6`

Current workaround:
Downgrade to `2.13.5`

**Comment by plokhotnyuk** [comment]
@akilegaspi Hi, Adrian! Thanks for reporting!

Please pick v2.13.10 release with a fix.

It is already available on the Maven Central: 
https://repo1.maven.org/maven2/com/github/plokhotnyuk/jsoniter-scala/jsoniter-scala-core_2.13/2.13.10/
