### ISSUE TITLE
Add support of default values for primitives when JSON value is null

### ISSUE THREAD

**Issue by plokhotnyuk** [plokhotnyuk/jsoniter-scala#88]
```
case class A(i: Int = 1)
readFromArray[A]("""{"i":null}""".getBytes) 
```
should return `A(1)`

**Comment by shawjef3** [comment]
I believe this deserialization should fail. If I were the client of such a JSON message, I would expect to use Option[Int] or java.lang.Integer, although I'd strongly prefer Option[Int].

**Comment by nilskp** [comment]
Agreed. Unless there's an explicit default value provided, this could lead to a hard-to-debug scenario.
