### ISSUE TITLE
Add circe-jawn to browser benchmarks?

### ISSUE THREAD

**Issue by armanbilge** [plokhotnyuk/jsoniter-scala#883]
In circe v0.15.0-M1 (released) and v0.14.2 (upcoming) the circe-jawn module is now cross-published for Scala.js. It's probably not important for this project, but since you maintain (the only?) Scala.js JSON benchmarks if you don't mind adding it I think it would be interesting to see the results.

We cross-published Jawn for Scala.js for situations where you need parsing on Scala.js with identical semantics to the JVM and/or advanced features such as streaming parsers. So I am curious how much of a performance penalty there is compared to using the JS-native JSON parser.

Feel free to close if this is not relevant to your project. Thanks! :)

**Comment by plokhotnyuk** [comment]
@armanbilge Please see results of Scala.js benchmarks with circe-jawn [here](https://plokhotnyuk.github.io/jsoniter-scala/index-scalajs.html)

Also, you can run Scala.js benchmarks on your browsers using [this page](https://plokhotnyuk.github.io/jsoniter-scala/scala-2.13-fullopt.html).

**Comment by armanbilge** [comment]
Wow, thank you so much!! That was very kind of you to add those to your benchmarks, much appreciated ❤️ I look forward to exploring them in detail.

**Comment by plokhotnyuk** [comment]
@armanbilge You are welcome!

Results on JVMs will be published in 2 days!
