### ISSUE TITLE
Consider adding of a code generation option to distinguish null and missing field (required for PATCH/partial PUT)

### ISSUE THREAD

**Issue by plokhotnyuk** [plokhotnyuk/jsoniter-scala#90]
Related to #30 in serialization

Try to don't repeat 1B$ mistake: https://www.infoq.com/presentations/Null-References-The-Billion-Dollar-Mistake-Tony-Hoare

**Comment by nilskp** [comment]
Yeah, just ran into this and couldn't work around it.

**Comment by plokhotnyuk** [comment]
Hi, @nilskp! Please share your example in a separate issue or in [the Gitter chat](https://gitter.im/plokhotnyuk/jsoniter-scala). It will try to find a suitable w/a for you...

**Comment by nilskp** [comment]
@plokhotnyuk 
I mentioned it a while back:
https://gitter.im/plokhotnyuk/jsoniter-scala?at=5b3b7f81a99e1e52b7125e00

**Comment by narma** [comment]
I have faced with the same issue previously. Same behavior  ( absence means "no change", null means remove, and presence of value means update ) is used in yandex.direct api https://tech.yandex.com/direct/doc/dg/best-practice/nillable-docpage/

**Comment by plokhotnyuk** [comment]
@nilskp @narma Closing with a W/A submitted into tests: https://github.com/plokhotnyuk/jsoniter-scala/commit/99e4ddac8521932e2c503742c1bd933315d00542

**Comment by plokhotnyuk** [comment]
There is also a project based on jsoniter-scala that solve subj for schema-less JSON: https://github.com/nrktkt/ninny-json
