### ISSUE TITLE
benchmark: jackson 2.14.0-SNAPSHOT

### ISSUE THREAD

**Issue by pjfanning** [plokhotnyuk/jsoniter-scala#907]
jackson 2.14.0-SNAPSHOT has some improvements.
* the issue that made the ArrayOfFloat test not work is fixed in this version
* there are now optional features to allow Double/Float parsing and writing using 'fast' algorithms
  * https://github.com/FasterXML/jackson-core/wiki/JsonReadFeatures documents how to set features
  * StreamReadFeature.USE_FAST_DOUBLE_PARSER
  * StreamWriteFeature.USE_FAST_DOUBLE_WRITER

**Comment by pjfanning** [comment]
thanks @plokhotnyuk - there is talk of creating a 2.14.0-RC1 in a few weeks

**Comment by plokhotnyuk** [comment]
> there is talk of creating a 2.14.0-RC1 in a few weeks

Waiting for any non-snapshot release with impatience ;) https://github.com/plokhotnyuk/jsoniter-scala/commit/84110f97eef69458cda30ccb6e0a00efd6f4402e
