### ISSUE TITLE
`requireCollectionFields` lacks documentation

### ISSUE THREAD

**Issue by linearray** [plokhotnyuk/jsoniter-scala#908]
All the fields in `CodecMakerConfig` have some documentation, except for `requireCollectionFields`.

https://github.com/plokhotnyuk/jsoniter-scala/blob/0b91ce22dad9eb08cf3441e3c5a28e9f95b444d4/jsoniter-scala-macros/shared/src/main/scala-3/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMaker.scala#L87

**Comment by plokhotnyuk** [comment]
Hi, Max! Thanks for the report!
