### ISSUE TITLE
Don't ignore named annotations when creating codec for inner type

### ISSUE THREAD

**Issue by shawjef3** [plokhotnyuk/jsoniter-scala#92]
See pull request #91.

This only seems to happen when there's no explicit codec for the inner class.

**Comment by plokhotnyuk** [comment]
It looks like a know problem of processing annotations with Scala macros: https://github.com/plokhotnyuk/jsoniter-scala/blob/1fabfee28cb3f5d92c0b5fdd3582e6a4e6f417d5/macros/src/test/scala/com/github/plokhotnyuk/jsoniter_scala/macros/JsonCodecMakerSpec.scala#L118

I will investigate if it is possible to manage it with a current version of macros.

As W/A it please don't c call `make` in the same source before usage of annotations in the case class definitions.

**Comment by shawjef3** [comment]
Excellent and quick work!
