### ISSUE TITLE
jackson issue with BitSet deserialization is fixed

### ISSUE THREAD

**Issue by pjfanning** [plokhotnyuk/jsoniter-scala#927]
There are a few benchmark tests disabled for jackson because BitSet deserialization did not work.

https://github.com/FasterXML/jackson-module-scala/issues/590 is fixed in latest 2.14.0-SNAPSHOT

I've changed the implementation so that you need to use `addModule(BitSetDeserializerModule)` as well as adding DefaultScalaModule. This avoids enabling support for BitSet deserialization by default.

**Comment by plokhotnyuk** [comment]
Just adding `BitSetDeserializerModule` doesn't help. Currently, a workarounf is adding deserializers for bit sets to the simple module.
