### ISSUE TITLE
Adding Fabric to Benchmark

### ISSUE THREAD

**Issue by darkfrog26** [plokhotnyuk/jsoniter-scala#943]
I'm interested in getting Fabric (https://github.com/outr/fabric) added to the benchmark. Should I just put together a PR to add support?

I've got my own benchmarks here compared against Circe and uPickle: https://jmh.morethan.io/?source=https://raw.githubusercontent.com/outr/fabric/master/bench/results/benchmarks-1.5.0.json

**Comment by plokhotnyuk** [comment]
Hi, Matt!

Sure, you can add a PR for benchmarking your library. Please try to cover as many benchmarks as possible. Then you can use them for tracking performance and checking security of your library.

Please take into account that jsoniter-scala parses from bytes and has benchmarks that parse from bytes. Yes, it has routines to parse from strings but only for testing purposes and as a workaround for cases when you have bytes in non-UTF-8 encoding and manually convert them to string with turned-on validation without lenient auto-replacement of malformed byte sequences. 

Your benchmarks parse from string and do not measure that you receive bytes from network or disk and do their conversion with auto-replacement of invalid UTF-8 or usually just differently encoded bytes to strings.

**Comment by darkfrog26** [comment]
Ugh...do you have any documentation of exactly where I should be adding my code? I'm finding it very difficult to parse through exactly where I should be injecting my code.

**Comment by plokhotnyuk** [comment]
Currently there are no written instructions for adding of benchmarks.

Probably looking through the commit history of the jsoniter-scala-benchmark directory will give you understanding of what and how it should be done.

I can guide you through the process if you will open a draft PR.

**Comment by darkfrog26** [comment]
Preliminary work done adding ADTReading and ADTWriting: https://github.com/plokhotnyuk/jsoniter-scala/pull/944

**Comment by plokhotnyuk** [comment]
Please and a call of your benchmark to the corresponding test in the `jvm` directory

**Comment by darkfrog26** [comment]
Ah, thanks, done!

**Comment by darkfrog26** [comment]
Looks like reading isn't terrible, but the writing is:
![75549DEC-C328-46A2-B3A8-F47F0EFBC1F9](https://user-images.githubusercontent.com/877534/190866141-fd30ff7f-dade-4525-907b-4b4d3acbe17f.jpeg)
![EDC2510A-DF71-4805-9A54-11EC1BF85400](https://user-images.githubusercontent.com/877534/190866142-2b8ba8e1-e011-453a-9a89-453eeefe52bb.jpeg)
If you wouldn't mind taking a look, I think I'm not optimally working with reading/writing to bytes.

**Comment by plokhotnyuk** [comment]
You can install async-profiler build flame graphs using the following command:
```
sbt jsoniter-scala-benchmarkJVM/clean 'jsoniter-scala-benchmarkJVM/jmh:run -prof "async:dir=target/async-reports;interval=1000000;output=flamegraph;libPath=/opt/async-profiler/build/libasyncProfiler.so" -jvmArgsAppend "-XX:+UnlockDiagnosticVMOptions -XX:+DebugNonSafepoints" --p size=128 -wi 5 -i 10 fabric'
```

**Comment by darkfrog26** [comment]
Thanks. It's a shame the benchmark doesn't support Scala 3. I have substantial optimizations that make Fabric much faster there.

**Comment by plokhotnyuk** [comment]
There are Scala 3 only JSON parsers... Now deciding to drop benchmarks for those which hasn't started migration to Scala 3 yet...

**Comment by plokhotnyuk** [comment]
The 1st wave of Scala 3 benchmarks is landed into the main branch: https://github.com/plokhotnyuk/jsoniter-scala/pull/956

**Comment by darkfrog26** [comment]
Very nice! Thanks for the heads up.
