### ISSUE TITLE
Issue with serializing / deserializing of ADTs

### ISSUE THREAD

**Issue by kyri-petrou** [plokhotnyuk/jsoniter-scala#949]
Hi there 👋

I'm not sure if this a known bug / feature or whether something can be tweaked in the configuration to enable this. In cases that we have a defined implicit codec for both the sealed trait and the leaf node, serializing the leaf node will always use the implicit of the leaf node regardless if the type is specified as the ADT. Subsequently, deserialization fails if we try to deserialize it as the ADT. Example:

```scala
import com.github.plokhotnyuk.jsoniter_scala.core._

sealed trait Pet {
  val name: String
}

object Pet {
  import com.github.plokhotnyuk.jsoniter_scala.macros._
  implicit val petCodec: JsonValueCodec[Pet] = JsonCodecMaker.make

  final case class Dog(name: String) extends Pet
  object Dog {
    implicit val dogCodec: JsonValueCodec[Dog] = JsonCodecMaker.make
  }
}

object Main {
  import Pet.Dog

  def serializePet(pet: Pet): String = writeToString[Pet](pet)
  def deserializePet(json: String): Pet = readFromString[Pet](json)

  def main(args: Array[String]): Unit = {
    val json = serializePet(Dog("Lassie"))
    readFromString[Dog](json) // Works
    deserializePet(json)  // Raises error
  }
}
```

fails with:

```
Exception in thread "main" com.github.plokhotnyuk.jsoniter_scala.core.JsonReaderException: expected key: "type", offset: 0x00000007, buf:
+----------+-------------------------------------------------+------------------+
|          |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f | 0123456789abcdef |
+----------+-------------------------------------------------+------------------+
| 00000000 | 7b 22 6e 61 6d 65 22 3a 22 4c 61 73 73 69 65 22 | {"name":"Lassie" |
| 00000010 | 7d                                              | }                |
+----------+-------------------------------------------------+------------------+
```

Where this becomes problematic is when we have serialize / deserialize other cases classes in the codebase, some of them having `Pet` and some others having `Dog` as a parameter. E.g., 

```scala
case class Person(name: String, pet: Option[Pet])
case class DogPerson(name: String, dog: Dog)
implicit val personCodec: JsonValueCodec[Person] = JsonCodecMaker.make
implicit val dogPersonCodec: JsonValueCodec[DogPerson] = JsonCodecMaker.make

readFromString[DogPerson](writeToString(DogPerson(...))) // works
readFromString[Person](writeToString(Person(...))) // error
```

Is there something that can be done in this case?

**Comment by plokhotnyuk** [comment]
`Pet` and `Dog` are different kind of types (sum and product types accordingly) so it is quite acceptable that macros generate different codecs that parse and write them differently.

**Comment by kyri-petrou** [comment]
> and use your top-level generated codecs: `personCodec` and `dogPersonCodec`

Thanks for this, that sorts out the issue! Being a user of `circe` for some time, I got too used to generating codecs for all the case classes / ADTs 😓

> Pet and Dog are different kind of types (sum and product types accordingly) so it is quite acceptable that macros generate different codecs that parse and write them differently.

I think that's fair enough and makes sense. Just a random idea - do you think it might be possible (and desirable) to get an "ambiguous implicit argument..." compiling error if we want to serialize a sealed trait and have the codec of a leaf node in scope?

**Comment by plokhotnyuk** [comment]
> > Pet and Dog are different kind of types (sum and product types accordingly) so it is quite acceptable that macros generate different codecs that parse and write them differently.
> 
> I think that's fair enough and makes sense. Just a random idea - do you think it might be possible (and desirable) to get an "ambiguous implicit argument..." compiling error if we want to serialize a sealed trait and have the codec of a leaf node in scope?

Codecs are invariant, so implicit arguments of codecs for `Pet` and `Dog` shouldn't collide.

**Comment by plokhotnyuk** [comment]
> > and use your top-level generated codecs: `personCodec` and `dogPersonCodec`
> 
> Thanks for this, that sorts out the issue! Being a user of `circe` for some time, I got too used to generating codecs for all the case classes / ADTs sweat

Thanks for sharing your experience! I will add a warning about that in the documentation.

**Comment by kyri-petrou** [comment]
Thanks again a lot for your help! Very much appreciated

**Comment by plokhotnyuk** [comment]
@kyri-petrou Thanks a bunch for your feedback! Happy coding and running with jsoniter-scala!
