### ISSUE TITLE
add json4s performance benchmark 

### ISSUE THREAD

**Issue by andyczerwonka** [plokhotnyuk/jsoniter-scala#952]
I’ve love to see numbers compared to https://github.com/json4s/json4s, for both the native and Jackson engines.

**Comment by plokhotnyuk** [comment]
BEWARE: json4s with both he native and Jackson engines is vulnerable under DoS attacks https://github.com/json4s/json4s/issues/554

I recommend migrate from it ASAP if your systems accept an untrusted JSON input.

**Comment by andyczerwonka** [comment]
In our case, no untrusted clients, but thanks for pointing that out. We definitely spend too much time on serde, so I’m looking for potential alternatives, which is why it’d be nice to bet the benchmark.

**Comment by plokhotnyuk** [comment]
@andyczerwonka I'm going to rerun all benchmarks on the next weekend and then will publish updated result charts.

**Comment by plokhotnyuk** [comment]
@andyczerwonka I've published benchmark results with json4s using 1 thread here: https://plokhotnyuk.github.io/jsoniter-scala/

To see allocation rate please select `gc.alloc.rate` item of `Score` drop-down list in the top right corner of the benchmark report page. Using this metric you can estimate scalability. Usually the limit for the total allocation rate is 1/3 of the memory bandwidth, so for host with 50Gb/sec memory bandwidth the limit for the total allocation rate will be 17Gb/sec.

**Comment by andyczerwonka** [comment]
> @andyczerwonka I've published benchmark results with json4s using 1 thread here: https://plokhotnyuk.github.io/jsoniter-scala/

Thank you @plokhotnyuk
