### ISSUE TITLE
anecdotal perf example

### ISSUE THREAD

**Issue by fommil** [plokhotnyuk/jsoniter-scala#96]
Sorry I can't share the ADT, but it's pretty simple, about 3 or 4 case classes deep, and max 9 fields, with options, strings, lists of strings, stringy maps... the usual. I thought you'd appreciate seeing these JMH results for some test data

```
[info] Benchmark                            Mode  Cnt        Score       Error  Units
[info] AccessTokenParsing.argonautConvert  thrpt    5   137158.136 ±  5942.009  ops/s
[info] AccessTokenParsing.playConvert      thrpt    5   150268.749 ±  9030.600  ops/s
[info] AccessTokenParsing.circeConvert     thrpt    5   421013.447 ± 13943.461  ops/s
[info] AccessTokenParsing.jsoniterConvert  thrpt    5  1083010.915 ± 24245.834  ops/s
[info] AccessTokenParsing.sprayConvert     thrpt    5   296858.901 ±  3482.840  ops/s

```

:astonished: 

(feel free to close when you've read this)

**Comment by plokhotnyuk** [comment]
It looks like and a perf issue because usually it outperforms circe ~4x times for ADTs: http://jmh.morethan.io/?source=https://plokhotnyuk.github.io/jsoniter-scala/jdk8.json

**Comment by fommil** [comment]
a byte array, I have a string.

**Comment by plokhotnyuk** [comment]
so, to transform String to byte array before parse by jsoniter-scala?

**Comment by fommil** [comment]
yes. I didn't see an API to read from a String.

**Comment by plokhotnyuk** [comment]
Why do you need string? Usually we parse from buffered UTF-8 bytes which are received from the wire or read from discs...

**Comment by fommil** [comment]
I have a `String`

**Comment by plokhotnyuk** [comment]
I see, but why?

**Comment by fommil** [comment]
because that's what I am given. This isn't something that I can negotiate with the API I have to work with.

**Comment by plokhotnyuk** [comment]
Is it open-sourced API?

**Comment by fommil** [comment]
no, sorry, that's why I said I can't share it. I just thought you'd be interested to see that it was so much faster than the others.

**Comment by plokhotnyuk** [comment]
ok, but, please, consider requesting an improvement for API, because you loose >2x times in perf due that redundant translations from strings...

**Comment by fommil** [comment]
Not until you support immutable stream input :-P

**Comment by plokhotnyuk** [comment]
ups... immutable stream of what? byte arrays?

**Comment by plokhotnyuk** [comment]
@fommil in any case, please ensure (by generative tests FTW), that bytes are encoded properly in UTF-8 format to avoid runtime-errors...

use .getBytes("UTF-8") everywhere to minimize human errors due copy-pasting: https://github.com/plokhotnyuk/jsoniter-scala/commit/979f4e3854d71db7d4707a86ec70c1107763f8a1
