### ISSUE TITLE
Asynchronous streaming reading/writing

### ISSUE THREAD

**Issue by armanbilge** [plokhotnyuk/jsoniter-scala#972]
If I understand correctly, streaming reading/writing is currently supported only with `InputStream` and `OutputStream`.

Unfortunately, `InputStream` and `OutputStream` are blocking APIs. This makes them inefficient to use since you have to run them on a separate blocking threadpool, which is bad for performance.

It would be interesting to offer async streaming APIs. I imagine that the reader/writer would have to preserve its intermediate state until it is invoked again (when there are more bytes to offer the reader, or the downstream is ready to take more bytes from the writer).

(Also relates to https://github.com/plokhotnyuk/jsoniter-scala/issues/296.)

**Comment by plokhotnyuk** [comment]
Currently there are 2 possible solutions:
1) using virtual threads from JDK19+
2) writing own intermediate buffer for raw bytes of JSON input that detects beginning and ending positions of JSON values and then call `readFromSubArray`

**Comment by armanbilge** [comment]
Thanks! Since you label as "question", does that mean this is a wontfix for jsoniter-scala?

**Comment by armanbilge** [comment]
> Any additional branches or access to memory have a great impact on `JsonReader` and `JsonWriter`, so I'm not going to alter them for working in asynchronous mode.

This makes sense to me. Thanks!
