### ISSUE TITLE
Top-level discriminators?

### ISSUE THREAD

**Issue by kubukoz** [plokhotnyuk/jsoniter-scala#993]
Hi! I've been looking at using jsoniter and so far like it quite a lot. I was wondering if it's possible to do this:

I want to use a custom decoder for one object key based on another key of that object.

Basically:

```jsonld
// `data` will be read using codec 1 - plain JSON
{"type": "JSON", "data": ""}

// `data` will be read as a string and decoded as base64
{"type": "Binary", "data": ""}
```

Sounds like discriminated unions, but there's a catch: this structure has a lot of other fields, and only one of them depends on the discriminator for its encoding.

To better explain what I mean, I have something like this:

```scala
case class Envelope[A](
  data: A,
  type: Type,
  // 10 more fields or so
)

sealed trait Type
object Type {
  case object JSON extends Type
  case object Binary extends Type
}
```

and I want to encode `data` using a custom codec (the implementation of that can be arbitrary, just rest assured that it produces _some_ JSON value, e.g. a base64-encoded string for binary encodings).

I don't think I can do that with the above structure and `JsonCodecMaker`. I was able to get the right result by merging the two types above:

```scala
sealed trait Envelope[A] {
  def data: A
  // 10 more fields or so
}

object Envelope {
  case class JSON[A](data: A, /*10 more fields*/) extends Envelope[A]
  case class Binary[A](data: A, /*10 more fields*/) extends Envelope[A]
}
```

and customizing the maker config: `withDiscriminatorFieldName(Some("type"))` - but clearly this isn't ideal for me,  because of the large amount of repetition in the `Envelope` subtypes.

**My question is:** Is there a better way to achieve the encoding I'm looking for, without handwriting my own codec entirely? What I _think_ would be the easiest is if I was able to move `A`'s discriminator to a top level somehow.

---

For some more context, originally I had something like

```scala
case class Envelope[A](
  data: Data,
  // 10 more fields or so
)

sealed trait Data
object Data {
  case class JSON(value: io.circe.Json) extends Data
  case class Binary(value: Array[Byte]) extends Data
}
```

and that was fine, but I want to avoid having an intermediate AST.

**Comment by plokhotnyuk** [comment]
Hi, Jakub!

Thanks for reaching me here! I'm happy to see that you are using jsoniter-scala.

If I understand correctly the data structures can be defined by us while message format is already defined and cannot be changed.

Please add message samples of both types for better understanding.

To prepare the best codec I need to know more context about how those `Envelope` values will be used after parsing.

**Comment by kubukoz** [comment]
Hey, after some consideration we decided we won't have a need for this, so I'll close for now. If I have a need for something similar in the future, I know where to find you :)
