### ISSUE TITLE
Question: parsing from different byte array representations

### ISSUE THREAD

**Issue by yoohaemin** [plokhotnyuk/jsoniter-scala#996]
Hi, thanks for the great library. I have a question.

Currently I understand that the library supports JSON parsing from `String`, `Array[Byte]`, `java.nio.ByteBuffer`, `java.io.InputStream`/`java.io.FileInputStream`.

However, I believe that many usecases will not directly deal with the above datatypes. For example, http4s would use `fs2.Stream[F, Byte]`, zio libs/apps may gravitate torwards `zio.Chunk[Byte]`, and others may use `scodec.bits.ByteVector` or some datatype somewhat equivalent to (immutable?) `IndexedSeq[Byte]`.

To parse from these datatypes, because many of them aren't exactly Arrays, they would have to be copied to one of the supported datatypes (I imagine mostly `Array` or `InputStream`) and then thrown away.

Will it be possible to expose a generic interface from this library that some other libraries or application code can implement/integrate, so copying into an intermediate `Array[Byte]` or `InputStream` becomes unnecessary?

Or would copying into an array usually be a better idea for better locality, and this is an unnecessary optimization?

**Comment by plokhotnyuk** [comment]
All generic collections introduces redundant boxing/unboxing that eats greatly CPU cycles and the memory bandwidth.

Moreover, Scala 3 doesn't support specialization for primitives currently.

Finally when parsing from `String`, `java.io.InputStream`, and `java.nio.DirectByteBuffer` the library does copying to `Array[Byte]` internally.

So the better option would be just copying to reusable instance of `Array[Byte]`.

**Comment by yoohaemin** [comment]
It makes sense to copy to reusable instance of Array[Byte]. Thank you!
